/*
 * This file is generated by jOOQ.
*/
package com.sukitsuki.bot.jooq.game.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Ability implements Serializable {

    private static final long serialVersionUID = -1567198715;

    private Integer abilityId;
    private String  name;
    private Integer abilityTypeId;
    private Short   requiredLevel;

    public Ability() {}

    public Ability(Ability value) {
        this.abilityId = value.abilityId;
        this.name = value.name;
        this.abilityTypeId = value.abilityTypeId;
        this.requiredLevel = value.requiredLevel;
    }

    public Ability(
        Integer abilityId,
        String  name,
        Integer abilityTypeId,
        Short   requiredLevel
    ) {
        this.abilityId = abilityId;
        this.name = name;
        this.abilityTypeId = abilityTypeId;
        this.requiredLevel = requiredLevel;
    }

    public Integer getAbilityId() {
        return this.abilityId;
    }

    public void setAbilityId(Integer abilityId) {
        this.abilityId = abilityId;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Integer getAbilityTypeId() {
        return this.abilityTypeId;
    }

    public void setAbilityTypeId(Integer abilityTypeId) {
        this.abilityTypeId = abilityTypeId;
    }

    public Short getRequiredLevel() {
        return this.requiredLevel;
    }

    public void setRequiredLevel(Short requiredLevel) {
        this.requiredLevel = requiredLevel;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Ability (");

        sb.append(abilityId);
        sb.append(", ").append(name);
        sb.append(", ").append(abilityTypeId);
        sb.append(", ").append(requiredLevel);

        sb.append(")");
        return sb.toString();
    }
}
