/*
 * This file is generated by jOOQ.
*/
package com.sukitsuki.bot.jooq.game.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AbilityType implements Serializable {

    private static final long serialVersionUID = 1229923570;

    private Integer abilityTypeId;
    private String  name;
    private String  desc;

    public AbilityType() {}

    public AbilityType(AbilityType value) {
        this.abilityTypeId = value.abilityTypeId;
        this.name = value.name;
        this.desc = value.desc;
    }

    public AbilityType(
        Integer abilityTypeId,
        String  name,
        String  desc
    ) {
        this.abilityTypeId = abilityTypeId;
        this.name = name;
        this.desc = desc;
    }

    public Integer getAbilityTypeId() {
        return this.abilityTypeId;
    }

    public void setAbilityTypeId(Integer abilityTypeId) {
        this.abilityTypeId = abilityTypeId;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getDesc() {
        return this.desc;
    }

    public void setDesc(String desc) {
        this.desc = desc;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("AbilityType (");

        sb.append(abilityTypeId);
        sb.append(", ").append(name);
        sb.append(", ").append(desc);

        sb.append(")");
        return sb.toString();
    }
}
