/*
 * This file is generated by jOOQ.
*/
package com.sukitsuki.bot.jooq.game.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CharacterLocation implements Serializable {

    private static final long serialVersionUID = -2119000428;

    private Integer characterLocationId;
    private Integer characterId;
    private Integer locationId;

    public CharacterLocation() {}

    public CharacterLocation(CharacterLocation value) {
        this.characterLocationId = value.characterLocationId;
        this.characterId = value.characterId;
        this.locationId = value.locationId;
    }

    public CharacterLocation(
        Integer characterLocationId,
        Integer characterId,
        Integer locationId
    ) {
        this.characterLocationId = characterLocationId;
        this.characterId = characterId;
        this.locationId = locationId;
    }

    public Integer getCharacterLocationId() {
        return this.characterLocationId;
    }

    public void setCharacterLocationId(Integer characterLocationId) {
        this.characterLocationId = characterLocationId;
    }

    public Integer getCharacterId() {
        return this.characterId;
    }

    public void setCharacterId(Integer characterId) {
        this.characterId = characterId;
    }

    public Integer getLocationId() {
        return this.locationId;
    }

    public void setLocationId(Integer locationId) {
        this.locationId = locationId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("CharacterLocation (");

        sb.append(characterLocationId);
        sb.append(", ").append(characterId);
        sb.append(", ").append(locationId);

        sb.append(")");
        return sb.toString();
    }
}
