/*
 * This file is generated by jOOQ.
*/
package com.sukitsuki.bot.jooq.game.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CharacterEquipment implements Serializable {

    private static final long serialVersionUID = 1802647340;

    private Integer characterEquipmentId;
    private Integer equipmentSlotId;
    private Integer characterId;
    private Integer itemId;

    public CharacterEquipment() {}

    public CharacterEquipment(CharacterEquipment value) {
        this.characterEquipmentId = value.characterEquipmentId;
        this.equipmentSlotId = value.equipmentSlotId;
        this.characterId = value.characterId;
        this.itemId = value.itemId;
    }

    public CharacterEquipment(
        Integer characterEquipmentId,
        Integer equipmentSlotId,
        Integer characterId,
        Integer itemId
    ) {
        this.characterEquipmentId = characterEquipmentId;
        this.equipmentSlotId = equipmentSlotId;
        this.characterId = characterId;
        this.itemId = itemId;
    }

    public Integer getCharacterEquipmentId() {
        return this.characterEquipmentId;
    }

    public void setCharacterEquipmentId(Integer characterEquipmentId) {
        this.characterEquipmentId = characterEquipmentId;
    }

    public Integer getEquipmentSlotId() {
        return this.equipmentSlotId;
    }

    public void setEquipmentSlotId(Integer equipmentSlotId) {
        this.equipmentSlotId = equipmentSlotId;
    }

    public Integer getCharacterId() {
        return this.characterId;
    }

    public void setCharacterId(Integer characterId) {
        this.characterId = characterId;
    }

    public Integer getItemId() {
        return this.itemId;
    }

    public void setItemId(Integer itemId) {
        this.itemId = itemId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("CharacterEquipment (");

        sb.append(characterEquipmentId);
        sb.append(", ").append(equipmentSlotId);
        sb.append(", ").append(characterId);
        sb.append(", ").append(itemId);

        sb.append(")");
        return sb.toString();
    }
}
