/*
 * This file is generated by jOOQ.
*/
package com.sukitsuki.bot.jooq.game.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CharacterGuild implements Serializable {

    private static final long serialVersionUID = 547749570;

    private Integer characterGuildId;
    private Integer characterId;
    private Integer guildId;
    private Boolean guildLeader;

    public CharacterGuild() {}

    public CharacterGuild(CharacterGuild value) {
        this.characterGuildId = value.characterGuildId;
        this.characterId = value.characterId;
        this.guildId = value.guildId;
        this.guildLeader = value.guildLeader;
    }

    public CharacterGuild(
        Integer characterGuildId,
        Integer characterId,
        Integer guildId,
        Boolean guildLeader
    ) {
        this.characterGuildId = characterGuildId;
        this.characterId = characterId;
        this.guildId = guildId;
        this.guildLeader = guildLeader;
    }

    public Integer getCharacterGuildId() {
        return this.characterGuildId;
    }

    public void setCharacterGuildId(Integer characterGuildId) {
        this.characterGuildId = characterGuildId;
    }

    public Integer getCharacterId() {
        return this.characterId;
    }

    public void setCharacterId(Integer characterId) {
        this.characterId = characterId;
    }

    public Integer getGuildId() {
        return this.guildId;
    }

    public void setGuildId(Integer guildId) {
        this.guildId = guildId;
    }

    public Boolean getGuildLeader() {
        return this.guildLeader;
    }

    public void setGuildLeader(Boolean guildLeader) {
        this.guildLeader = guildLeader;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("CharacterGuild (");

        sb.append(characterGuildId);
        sb.append(", ").append(characterId);
        sb.append(", ").append(guildId);
        sb.append(", ").append(guildLeader);

        sb.append(")");
        return sb.toString();
    }
}
