/*
 * This file is generated by jOOQ.
*/
package com.sukitsuki.bot.jooq.game.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CharacterFaction implements Serializable {

    private static final long serialVersionUID = 2126330722;

    private Integer characterFactionId;
    private Integer characterId;
    private Integer factionId;

    public CharacterFaction() {}

    public CharacterFaction(CharacterFaction value) {
        this.characterFactionId = value.characterFactionId;
        this.characterId = value.characterId;
        this.factionId = value.factionId;
    }

    public CharacterFaction(
        Integer characterFactionId,
        Integer characterId,
        Integer factionId
    ) {
        this.characterFactionId = characterFactionId;
        this.characterId = characterId;
        this.factionId = factionId;
    }

    public Integer getCharacterFactionId() {
        return this.characterFactionId;
    }

    public void setCharacterFactionId(Integer characterFactionId) {
        this.characterFactionId = characterFactionId;
    }

    public Integer getCharacterId() {
        return this.characterId;
    }

    public void setCharacterId(Integer characterId) {
        this.characterId = characterId;
    }

    public Integer getFactionId() {
        return this.factionId;
    }

    public void setFactionId(Integer factionId) {
        this.factionId = factionId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("CharacterFaction (");

        sb.append(characterFactionId);
        sb.append(", ").append(characterId);
        sb.append(", ").append(factionId);

        sb.append(")");
        return sb.toString();
    }
}
