/*
 * This file is generated by jOOQ.
*/
package com.sukitsuki.bot.jooq.game.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CharacterTitle implements Serializable {

    private static final long serialVersionUID = 684398882;

    private Integer characterTitleId;
    private Integer characterId;
    private Integer titleId;

    public CharacterTitle() {}

    public CharacterTitle(CharacterTitle value) {
        this.characterTitleId = value.characterTitleId;
        this.characterId = value.characterId;
        this.titleId = value.titleId;
    }

    public CharacterTitle(
        Integer characterTitleId,
        Integer characterId,
        Integer titleId
    ) {
        this.characterTitleId = characterTitleId;
        this.characterId = characterId;
        this.titleId = titleId;
    }

    public Integer getCharacterTitleId() {
        return this.characterTitleId;
    }

    public void setCharacterTitleId(Integer characterTitleId) {
        this.characterTitleId = characterTitleId;
    }

    public Integer getCharacterId() {
        return this.characterId;
    }

    public void setCharacterId(Integer characterId) {
        this.characterId = characterId;
    }

    public Integer getTitleId() {
        return this.titleId;
    }

    public void setTitleId(Integer titleId) {
        this.titleId = titleId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("CharacterTitle (");

        sb.append(characterTitleId);
        sb.append(", ").append(characterId);
        sb.append(", ").append(titleId);

        sb.append(")");
        return sb.toString();
    }
}
