/*
 * This file is generated by jOOQ.
*/
package com.sukitsuki.bot.jooq.game.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Class implements Serializable {

    private static final long serialVersionUID = 683404767;

    private Integer classId;
    private String  name;

    public Class() {}

    public Class(Class value) {
        this.classId = value.classId;
        this.name = value.name;
    }

    public Class(
        Integer classId,
        String  name
    ) {
        this.classId = classId;
        this.name = name;
    }

    public Integer getClassId() {
        return this.classId;
    }

    public void setClassId(Integer classId) {
        this.classId = classId;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Class (");

        sb.append(classId);
        sb.append(", ").append(name);

        sb.append(")");
        return sb.toString();
    }
}
