/*
 * This file is generated by jOOQ.
*/
package com.sukitsuki.bot.jooq.game.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Conf implements Serializable {

    private static final long serialVersionUID = 1864964916;

    private Integer confId;
    private String  name;
    private String  value;

    public Conf() {}

    public Conf(Conf value) {
        this.confId = value.confId;
        this.name = value.name;
        this.value = value.value;
    }

    public Conf(
        Integer confId,
        String  name,
        String  value
    ) {
        this.confId = confId;
        this.name = name;
        this.value = value;
    }

    public Integer getConfId() {
        return this.confId;
    }

    public void setConfId(Integer confId) {
        this.confId = confId;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getValue() {
        return this.value;
    }

    public void setValue(String value) {
        this.value = value;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Conf (");

        sb.append(confId);
        sb.append(", ").append(name);
        sb.append(", ").append(value);

        sb.append(")");
        return sb.toString();
    }
}
