/*
 * This file is generated by jOOQ.
*/
package com.sukitsuki.bot.jooq.game.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EffectType implements Serializable {

    private static final long serialVersionUID = 1758842385;

    private Integer effectTypeId;
    private String  name;
    private String  desc;

    public EffectType() {}

    public EffectType(EffectType value) {
        this.effectTypeId = value.effectTypeId;
        this.name = value.name;
        this.desc = value.desc;
    }

    public EffectType(
        Integer effectTypeId,
        String  name,
        String  desc
    ) {
        this.effectTypeId = effectTypeId;
        this.name = name;
        this.desc = desc;
    }

    public Integer getEffectTypeId() {
        return this.effectTypeId;
    }

    public void setEffectTypeId(Integer effectTypeId) {
        this.effectTypeId = effectTypeId;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getDesc() {
        return this.desc;
    }

    public void setDesc(String desc) {
        this.desc = desc;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("EffectType (");

        sb.append(effectTypeId);
        sb.append(", ").append(name);
        sb.append(", ").append(desc);

        sb.append(")");
        return sb.toString();
    }
}
