/*
 * This file is generated by jOOQ.
*/
package com.sukitsuki.bot.jooq.game.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EntityAttribute implements Serializable {

    private static final long serialVersionUID = 498532881;

    private Integer entityAttributeId;
    private Integer entityId;
    private Integer attributeId;
    private Long    value;

    public EntityAttribute() {}

    public EntityAttribute(EntityAttribute value) {
        this.entityAttributeId = value.entityAttributeId;
        this.entityId = value.entityId;
        this.attributeId = value.attributeId;
        this.value = value.value;
    }

    public EntityAttribute(
        Integer entityAttributeId,
        Integer entityId,
        Integer attributeId,
        Long    value
    ) {
        this.entityAttributeId = entityAttributeId;
        this.entityId = entityId;
        this.attributeId = attributeId;
        this.value = value;
    }

    public Integer getEntityAttributeId() {
        return this.entityAttributeId;
    }

    public void setEntityAttributeId(Integer entityAttributeId) {
        this.entityAttributeId = entityAttributeId;
    }

    public Integer getEntityId() {
        return this.entityId;
    }

    public void setEntityId(Integer entityId) {
        this.entityId = entityId;
    }

    public Integer getAttributeId() {
        return this.attributeId;
    }

    public void setAttributeId(Integer attributeId) {
        this.attributeId = attributeId;
    }

    public Long getValue() {
        return this.value;
    }

    public void setValue(Long value) {
        this.value = value;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("EntityAttribute (");

        sb.append(entityAttributeId);
        sb.append(", ").append(entityId);
        sb.append(", ").append(attributeId);
        sb.append(", ").append(value);

        sb.append(")");
        return sb.toString();
    }
}
