/*
 * This file is generated by jOOQ.
*/
package com.sukitsuki.bot.jooq.game.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EntityClass implements Serializable {

    private static final long serialVersionUID = 1030413672;

    private Integer entityClassId;
    private Integer entityId;
    private Integer classId;

    public EntityClass() {}

    public EntityClass(EntityClass value) {
        this.entityClassId = value.entityClassId;
        this.entityId = value.entityId;
        this.classId = value.classId;
    }

    public EntityClass(
        Integer entityClassId,
        Integer entityId,
        Integer classId
    ) {
        this.entityClassId = entityClassId;
        this.entityId = entityId;
        this.classId = classId;
    }

    public Integer getEntityClassId() {
        return this.entityClassId;
    }

    public void setEntityClassId(Integer entityClassId) {
        this.entityClassId = entityClassId;
    }

    public Integer getEntityId() {
        return this.entityId;
    }

    public void setEntityId(Integer entityId) {
        this.entityId = entityId;
    }

    public Integer getClassId() {
        return this.classId;
    }

    public void setClassId(Integer classId) {
        this.classId = classId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("EntityClass (");

        sb.append(entityClassId);
        sb.append(", ").append(entityId);
        sb.append(", ").append(classId);

        sb.append(")");
        return sb.toString();
    }
}
