/*
 * This file is generated by jOOQ.
*/
package com.sukitsuki.bot.jooq.game.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EntityType implements Serializable {

    private static final long serialVersionUID = 1960555074;

    private Integer entityTypeId;
    private String  name;

    public EntityType() {}

    public EntityType(EntityType value) {
        this.entityTypeId = value.entityTypeId;
        this.name = value.name;
    }

    public EntityType(
        Integer entityTypeId,
        String  name
    ) {
        this.entityTypeId = entityTypeId;
        this.name = name;
    }

    public Integer getEntityTypeId() {
        return this.entityTypeId;
    }

    public void setEntityTypeId(Integer entityTypeId) {
        this.entityTypeId = entityTypeId;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("EntityType (");

        sb.append(entityTypeId);
        sb.append(", ").append(name);

        sb.append(")");
        return sb.toString();
    }
}
