/*
 * This file is generated by jOOQ.
*/
package com.sukitsuki.bot.jooq.game.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EntityLocation implements Serializable {

    private static final long serialVersionUID = 1152314044;

    private Integer entityLocationId;
    private Integer entityId;
    private Integer locationId;

    public EntityLocation() {}

    public EntityLocation(EntityLocation value) {
        this.entityLocationId = value.entityLocationId;
        this.entityId = value.entityId;
        this.locationId = value.locationId;
    }

    public EntityLocation(
        Integer entityLocationId,
        Integer entityId,
        Integer locationId
    ) {
        this.entityLocationId = entityLocationId;
        this.entityId = entityId;
        this.locationId = locationId;
    }

    public Integer getEntityLocationId() {
        return this.entityLocationId;
    }

    public void setEntityLocationId(Integer entityLocationId) {
        this.entityLocationId = entityLocationId;
    }

    public Integer getEntityId() {
        return this.entityId;
    }

    public void setEntityId(Integer entityId) {
        this.entityId = entityId;
    }

    public Integer getLocationId() {
        return this.locationId;
    }

    public void setLocationId(Integer locationId) {
        this.locationId = locationId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("EntityLocation (");

        sb.append(entityLocationId);
        sb.append(", ").append(entityId);
        sb.append(", ").append(locationId);

        sb.append(")");
        return sb.toString();
    }
}
