/*
 * This file is generated by jOOQ.
*/
package com.sukitsuki.bot.jooq.game.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EntityFaction implements Serializable {

    private static final long serialVersionUID = -1874004784;

    private Integer entityFactionId;
    private Integer entityId;
    private Integer factionId;

    public EntityFaction() {}

    public EntityFaction(EntityFaction value) {
        this.entityFactionId = value.entityFactionId;
        this.entityId = value.entityId;
        this.factionId = value.factionId;
    }

    public EntityFaction(
        Integer entityFactionId,
        Integer entityId,
        Integer factionId
    ) {
        this.entityFactionId = entityFactionId;
        this.entityId = entityId;
        this.factionId = factionId;
    }

    public Integer getEntityFactionId() {
        return this.entityFactionId;
    }

    public void setEntityFactionId(Integer entityFactionId) {
        this.entityFactionId = entityFactionId;
    }

    public Integer getEntityId() {
        return this.entityId;
    }

    public void setEntityId(Integer entityId) {
        this.entityId = entityId;
    }

    public Integer getFactionId() {
        return this.factionId;
    }

    public void setFactionId(Integer factionId) {
        this.factionId = factionId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("EntityFaction (");

        sb.append(entityFactionId);
        sb.append(", ").append(entityId);
        sb.append(", ").append(factionId);

        sb.append(")");
        return sb.toString();
    }
}
