/*
 * This file is generated by jOOQ.
*/
package com.sukitsuki.bot.jooq.game.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EquipmentSlot implements Serializable {

    private static final long serialVersionUID = -1481688733;

    private Integer equipmentSlotId;
    private String  name;

    public EquipmentSlot() {}

    public EquipmentSlot(EquipmentSlot value) {
        this.equipmentSlotId = value.equipmentSlotId;
        this.name = value.name;
    }

    public EquipmentSlot(
        Integer equipmentSlotId,
        String  name
    ) {
        this.equipmentSlotId = equipmentSlotId;
        this.name = name;
    }

    public Integer getEquipmentSlotId() {
        return this.equipmentSlotId;
    }

    public void setEquipmentSlotId(Integer equipmentSlotId) {
        this.equipmentSlotId = equipmentSlotId;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("EquipmentSlot (");

        sb.append(equipmentSlotId);
        sb.append(", ").append(name);

        sb.append(")");
        return sb.toString();
    }
}
