/*
 * This file is generated by jOOQ.
*/
package com.sukitsuki.bot.jooq.game.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Faction implements Serializable {

    private static final long serialVersionUID = -424451949;

    private Integer factionId;
    private String  name;

    public Faction() {}

    public Faction(Faction value) {
        this.factionId = value.factionId;
        this.name = value.name;
    }

    public Faction(
        Integer factionId,
        String  name
    ) {
        this.factionId = factionId;
        this.name = name;
    }

    public Integer getFactionId() {
        return this.factionId;
    }

    public void setFactionId(Integer factionId) {
        this.factionId = factionId;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Faction (");

        sb.append(factionId);
        sb.append(", ").append(name);

        sb.append(")");
        return sb.toString();
    }
}
