/*
 * This file is generated by jOOQ.
*/
package com.sukitsuki.bot.jooq.game.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ItemAttribute implements Serializable {

    private static final long serialVersionUID = 690973361;

    private Integer itemAttributeId;
    private Integer itemId;
    private Integer attributeId;
    private Long    value;

    public ItemAttribute() {}

    public ItemAttribute(ItemAttribute value) {
        this.itemAttributeId = value.itemAttributeId;
        this.itemId = value.itemId;
        this.attributeId = value.attributeId;
        this.value = value.value;
    }

    public ItemAttribute(
        Integer itemAttributeId,
        Integer itemId,
        Integer attributeId,
        Long    value
    ) {
        this.itemAttributeId = itemAttributeId;
        this.itemId = itemId;
        this.attributeId = attributeId;
        this.value = value;
    }

    public Integer getItemAttributeId() {
        return this.itemAttributeId;
    }

    public void setItemAttributeId(Integer itemAttributeId) {
        this.itemAttributeId = itemAttributeId;
    }

    public Integer getItemId() {
        return this.itemId;
    }

    public void setItemId(Integer itemId) {
        this.itemId = itemId;
    }

    public Integer getAttributeId() {
        return this.attributeId;
    }

    public void setAttributeId(Integer attributeId) {
        this.attributeId = attributeId;
    }

    public Long getValue() {
        return this.value;
    }

    public void setValue(Long value) {
        this.value = value;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ItemAttribute (");

        sb.append(itemAttributeId);
        sb.append(", ").append(itemId);
        sb.append(", ").append(attributeId);
        sb.append(", ").append(value);

        sb.append(")");
        return sb.toString();
    }
}
