/*
 * This file is generated by jOOQ.
*/
package com.sukitsuki.bot.jooq.game.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ItemLocation implements Serializable {

    private static final long serialVersionUID = 532439452;

    private Integer itemLocationId;
    private Integer itemId;
    private Integer locationId;

    public ItemLocation() {}

    public ItemLocation(ItemLocation value) {
        this.itemLocationId = value.itemLocationId;
        this.itemId = value.itemId;
        this.locationId = value.locationId;
    }

    public ItemLocation(
        Integer itemLocationId,
        Integer itemId,
        Integer locationId
    ) {
        this.itemLocationId = itemLocationId;
        this.itemId = itemId;
        this.locationId = locationId;
    }

    public Integer getItemLocationId() {
        return this.itemLocationId;
    }

    public void setItemLocationId(Integer itemLocationId) {
        this.itemLocationId = itemLocationId;
    }

    public Integer getItemId() {
        return this.itemId;
    }

    public void setItemId(Integer itemId) {
        this.itemId = itemId;
    }

    public Integer getLocationId() {
        return this.locationId;
    }

    public void setLocationId(Integer locationId) {
        this.locationId = locationId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ItemLocation (");

        sb.append(itemLocationId);
        sb.append(", ").append(itemId);
        sb.append(", ").append(locationId);

        sb.append(")");
        return sb.toString();
    }
}
