/*
 * This file is generated by jOOQ.
*/
package com.sukitsuki.bot.jooq.game.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Location implements Serializable {

    private static final long serialVersionUID = -1866641916;

    private Integer locationId;
    private Long    x;
    private Long    y;
    private Integer placeId;

    public Location() {}

    public Location(Location value) {
        this.locationId = value.locationId;
        this.x = value.x;
        this.y = value.y;
        this.placeId = value.placeId;
    }

    public Location(
        Integer locationId,
        Long    x,
        Long    y,
        Integer placeId
    ) {
        this.locationId = locationId;
        this.x = x;
        this.y = y;
        this.placeId = placeId;
    }

    public Integer getLocationId() {
        return this.locationId;
    }

    public void setLocationId(Integer locationId) {
        this.locationId = locationId;
    }

    public Long getX() {
        return this.x;
    }

    public void setX(Long x) {
        this.x = x;
    }

    public Long getY() {
        return this.y;
    }

    public void setY(Long y) {
        this.y = y;
    }

    public Integer getPlaceId() {
        return this.placeId;
    }

    public void setPlaceId(Integer placeId) {
        this.placeId = placeId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Location (");

        sb.append(locationId);
        sb.append(", ").append(x);
        sb.append(", ").append(y);
        sb.append(", ").append(placeId);

        sb.append(")");
        return sb.toString();
    }
}
