/*
 * This file is generated by jOOQ.
*/
package com.sukitsuki.bot.jooq.game.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Loot implements Serializable {

    private static final long serialVersionUID = 1406507774;

    private Integer lootId;
    private Long    xp;
    private Long    money;

    public Loot() {}

    public Loot(Loot value) {
        this.lootId = value.lootId;
        this.xp = value.xp;
        this.money = value.money;
    }

    public Loot(
        Integer lootId,
        Long    xp,
        Long    money
    ) {
        this.lootId = lootId;
        this.xp = xp;
        this.money = money;
    }

    public Integer getLootId() {
        return this.lootId;
    }

    public void setLootId(Integer lootId) {
        this.lootId = lootId;
    }

    public Long getXp() {
        return this.xp;
    }

    public void setXp(Long xp) {
        this.xp = xp;
    }

    public Long getMoney() {
        return this.money;
    }

    public void setMoney(Long money) {
        this.money = money;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Loot (");

        sb.append(lootId);
        sb.append(", ").append(xp);
        sb.append(", ").append(money);

        sb.append(")");
        return sb.toString();
    }
}
