/*
 * This file is generated by jOOQ.
*/
package com.sukitsuki.bot.jooq.game.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Place implements Serializable {

    private static final long serialVersionUID = 881411402;

    private Integer placeId;
    private String  name;

    public Place() {}

    public Place(Place value) {
        this.placeId = value.placeId;
        this.name = value.name;
    }

    public Place(
        Integer placeId,
        String  name
    ) {
        this.placeId = placeId;
        this.name = name;
    }

    public Integer getPlaceId() {
        return this.placeId;
    }

    public void setPlaceId(Integer placeId) {
        this.placeId = placeId;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Place (");

        sb.append(placeId);
        sb.append(", ").append(name);

        sb.append(")");
        return sb.toString();
    }
}
