/*
 * This file is generated by jOOQ.
*/
package com.sukitsuki.bot.jooq.game.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class StatusEffect implements Serializable {

    private static final long serialVersionUID = -1572872673;

    private Integer statusEffectId;
    private String  name;
    private Integer effectTypeId;
    private Long    duration;
    private String  desc;

    public StatusEffect() {}

    public StatusEffect(StatusEffect value) {
        this.statusEffectId = value.statusEffectId;
        this.name = value.name;
        this.effectTypeId = value.effectTypeId;
        this.duration = value.duration;
        this.desc = value.desc;
    }

    public StatusEffect(
        Integer statusEffectId,
        String  name,
        Integer effectTypeId,
        Long    duration,
        String  desc
    ) {
        this.statusEffectId = statusEffectId;
        this.name = name;
        this.effectTypeId = effectTypeId;
        this.duration = duration;
        this.desc = desc;
    }

    public Integer getStatusEffectId() {
        return this.statusEffectId;
    }

    public void setStatusEffectId(Integer statusEffectId) {
        this.statusEffectId = statusEffectId;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Integer getEffectTypeId() {
        return this.effectTypeId;
    }

    public void setEffectTypeId(Integer effectTypeId) {
        this.effectTypeId = effectTypeId;
    }

    public Long getDuration() {
        return this.duration;
    }

    public void setDuration(Long duration) {
        this.duration = duration;
    }

    public String getDesc() {
        return this.desc;
    }

    public void setDesc(String desc) {
        this.desc = desc;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("StatusEffect (");

        sb.append(statusEffectId);
        sb.append(", ").append(name);
        sb.append(", ").append(effectTypeId);
        sb.append(", ").append(duration);
        sb.append(", ").append(desc);

        sb.append(")");
        return sb.toString();
    }
}
