/*
 * This file is generated by jOOQ.
*/
package com.sukitsuki.bot.jooq.game.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Title implements Serializable {

    private static final long serialVersionUID = 569908799;

    private Integer titleId;
    private String  name;

    public Title() {}

    public Title(Title value) {
        this.titleId = value.titleId;
        this.name = value.name;
    }

    public Title(
        Integer titleId,
        String  name
    ) {
        this.titleId = titleId;
        this.name = name;
    }

    public Integer getTitleId() {
        return this.titleId;
    }

    public void setTitleId(Integer titleId) {
        this.titleId = titleId;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Title (");

        sb.append(titleId);
        sb.append(", ").append(name);

        sb.append(")");
        return sb.toString();
    }
}
