/*
 * This file is generated by jOOQ.
*/
package com.sukitsuki.bot.jooq.game.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserCharacter implements Serializable {

    private static final long serialVersionUID = 1646753090;

    private Integer userCharacterId;
    private Integer userId;
    private Integer characterId;

    public UserCharacter() {}

    public UserCharacter(UserCharacter value) {
        this.userCharacterId = value.userCharacterId;
        this.userId = value.userId;
        this.characterId = value.characterId;
    }

    public UserCharacter(
        Integer userCharacterId,
        Integer userId,
        Integer characterId
    ) {
        this.userCharacterId = userCharacterId;
        this.userId = userId;
        this.characterId = characterId;
    }

    public Integer getUserCharacterId() {
        return this.userCharacterId;
    }

    public void setUserCharacterId(Integer userCharacterId) {
        this.userCharacterId = userCharacterId;
    }

    public Integer getUserId() {
        return this.userId;
    }

    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    public Integer getCharacterId() {
        return this.characterId;
    }

    public void setCharacterId(Integer characterId) {
        this.characterId = characterId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("UserCharacter (");

        sb.append(userCharacterId);
        sb.append(", ").append(userId);
        sb.append(", ").append(characterId);

        sb.append(")");
        return sb.toString();
    }
}
