/*
 * This file is generated by jOOQ.
*/
package com.sukitsuki.bot.jooq.game.tables.records;


import com.sukitsuki.bot.jooq.game.tables.CharacterLocation;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CharacterLocationRecord extends UpdatableRecordImpl<CharacterLocationRecord> implements Record3<Integer, Integer, Integer> {

    private static final long serialVersionUID = -1693405379;

    /**
     * Setter for <code>game.character_location.character_location_id</code>.
     */
    public void setCharacterLocationId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>game.character_location.character_location_id</code>.
     */
    public Integer getCharacterLocationId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>game.character_location.character_id</code>.
     */
    public void setCharacterId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>game.character_location.character_id</code>.
     */
    public Integer getCharacterId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>game.character_location.location_id</code>.
     */
    public void setLocationId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>game.character_location.location_id</code>.
     */
    public Integer getLocationId() {
        return (Integer) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Integer, Integer, Integer> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Integer, Integer, Integer> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return CharacterLocation.CHARACTER_LOCATION.CHARACTER_LOCATION_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return CharacterLocation.CHARACTER_LOCATION.CHARACTER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return CharacterLocation.CHARACTER_LOCATION.LOCATION_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getCharacterLocationId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getCharacterId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getLocationId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CharacterLocationRecord value1(Integer value) {
        setCharacterLocationId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CharacterLocationRecord value2(Integer value) {
        setCharacterId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CharacterLocationRecord value3(Integer value) {
        setLocationId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CharacterLocationRecord values(Integer value1, Integer value2, Integer value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CharacterLocationRecord
     */
    public CharacterLocationRecord() {
        super(CharacterLocation.CHARACTER_LOCATION);
    }

    /**
     * Create a detached, initialised CharacterLocationRecord
     */
    public CharacterLocationRecord(Integer characterLocationId, Integer characterId, Integer locationId) {
        super(CharacterLocation.CHARACTER_LOCATION);

        set(0, characterLocationId);
        set(1, characterId);
        set(2, locationId);
    }
}
