/*
 * This file is generated by jOOQ.
*/
package com.sukitsuki.bot.jooq.game.tables.records;


import com.sukitsuki.bot.jooq.game.tables.CharacterEquipment;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CharacterEquipmentRecord extends UpdatableRecordImpl<CharacterEquipmentRecord> implements Record4<Integer, Integer, Integer, Integer> {

    private static final long serialVersionUID = 680269013;

    /**
     * Setter for <code>game.character_equipment.character_equipment_id</code>.
     */
    public void setCharacterEquipmentId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>game.character_equipment.character_equipment_id</code>.
     */
    public Integer getCharacterEquipmentId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>game.character_equipment.equipment_slot_id</code>.
     */
    public void setEquipmentSlotId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>game.character_equipment.equipment_slot_id</code>.
     */
    public Integer getEquipmentSlotId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>game.character_equipment.character_id</code>.
     */
    public void setCharacterId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>game.character_equipment.character_id</code>.
     */
    public Integer getCharacterId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>game.character_equipment.item_id</code>.
     */
    public void setItemId(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>game.character_equipment.item_id</code>.
     */
    public Integer getItemId() {
        return (Integer) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Integer, Integer, Integer, Integer> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Integer, Integer, Integer, Integer> valuesRow() {
        return (Row4) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return CharacterEquipment.CHARACTER_EQUIPMENT.CHARACTER_EQUIPMENT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return CharacterEquipment.CHARACTER_EQUIPMENT.EQUIPMENT_SLOT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return CharacterEquipment.CHARACTER_EQUIPMENT.CHARACTER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return CharacterEquipment.CHARACTER_EQUIPMENT.ITEM_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getCharacterEquipmentId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getEquipmentSlotId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getCharacterId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getItemId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CharacterEquipmentRecord value1(Integer value) {
        setCharacterEquipmentId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CharacterEquipmentRecord value2(Integer value) {
        setEquipmentSlotId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CharacterEquipmentRecord value3(Integer value) {
        setCharacterId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CharacterEquipmentRecord value4(Integer value) {
        setItemId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CharacterEquipmentRecord values(Integer value1, Integer value2, Integer value3, Integer value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CharacterEquipmentRecord
     */
    public CharacterEquipmentRecord() {
        super(CharacterEquipment.CHARACTER_EQUIPMENT);
    }

    /**
     * Create a detached, initialised CharacterEquipmentRecord
     */
    public CharacterEquipmentRecord(Integer characterEquipmentId, Integer equipmentSlotId, Integer characterId, Integer itemId) {
        super(CharacterEquipment.CHARACTER_EQUIPMENT);

        set(0, characterEquipmentId);
        set(1, equipmentSlotId);
        set(2, characterId);
        set(3, itemId);
    }
}
