/*
 * This file is generated by jOOQ.
*/
package com.sukitsuki.bot.jooq.game.tables.records;


import com.sukitsuki.bot.jooq.game.tables.CharacterGuild;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CharacterGuildRecord extends UpdatableRecordImpl<CharacterGuildRecord> implements Record4<Integer, Integer, Integer, Boolean> {

    private static final long serialVersionUID = 660428904;

    /**
     * Setter for <code>game.character_guild.character_guild_id</code>.
     */
    public void setCharacterGuildId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>game.character_guild.character_guild_id</code>.
     */
    public Integer getCharacterGuildId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>game.character_guild.character_id</code>.
     */
    public void setCharacterId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>game.character_guild.character_id</code>.
     */
    public Integer getCharacterId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>game.character_guild.guild_id</code>.
     */
    public void setGuildId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>game.character_guild.guild_id</code>.
     */
    public Integer getGuildId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>game.character_guild.guild_leader</code>.
     */
    public void setGuildLeader(Boolean value) {
        set(3, value);
    }

    /**
     * Getter for <code>game.character_guild.guild_leader</code>.
     */
    public Boolean getGuildLeader() {
        return (Boolean) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Integer, Integer, Integer, Boolean> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Integer, Integer, Integer, Boolean> valuesRow() {
        return (Row4) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return CharacterGuild.CHARACTER_GUILD.CHARACTER_GUILD_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return CharacterGuild.CHARACTER_GUILD.CHARACTER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return CharacterGuild.CHARACTER_GUILD.GUILD_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field4() {
        return CharacterGuild.CHARACTER_GUILD.GUILD_LEADER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getCharacterGuildId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getCharacterId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getGuildId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value4() {
        return getGuildLeader();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CharacterGuildRecord value1(Integer value) {
        setCharacterGuildId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CharacterGuildRecord value2(Integer value) {
        setCharacterId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CharacterGuildRecord value3(Integer value) {
        setGuildId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CharacterGuildRecord value4(Boolean value) {
        setGuildLeader(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CharacterGuildRecord values(Integer value1, Integer value2, Integer value3, Boolean value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CharacterGuildRecord
     */
    public CharacterGuildRecord() {
        super(CharacterGuild.CHARACTER_GUILD);
    }

    /**
     * Create a detached, initialised CharacterGuildRecord
     */
    public CharacterGuildRecord(Integer characterGuildId, Integer characterId, Integer guildId, Boolean guildLeader) {
        super(CharacterGuild.CHARACTER_GUILD);

        set(0, characterGuildId);
        set(1, characterId);
        set(2, guildId);
        set(3, guildLeader);
    }
}
