/*
 * This file is generated by jOOQ.
*/
package com.sukitsuki.bot.jooq.game.tables.records;


import com.sukitsuki.bot.jooq.game.tables.CharacterItem;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CharacterItemRecord extends UpdatableRecordImpl<CharacterItemRecord> implements Record3<Integer, Integer, Integer> {

    private static final long serialVersionUID = 88302883;

    /**
     * Setter for <code>game.character_item.character_item_id</code>.
     */
    public void setCharacterItemId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>game.character_item.character_item_id</code>.
     */
    public Integer getCharacterItemId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>game.character_item.character_id</code>.
     */
    public void setCharacterId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>game.character_item.character_id</code>.
     */
    public Integer getCharacterId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>game.character_item.item_id</code>.
     */
    public void setItemId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>game.character_item.item_id</code>.
     */
    public Integer getItemId() {
        return (Integer) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Integer, Integer, Integer> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Integer, Integer, Integer> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return CharacterItem.CHARACTER_ITEM.CHARACTER_ITEM_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return CharacterItem.CHARACTER_ITEM.CHARACTER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return CharacterItem.CHARACTER_ITEM.ITEM_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getCharacterItemId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getCharacterId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getItemId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CharacterItemRecord value1(Integer value) {
        setCharacterItemId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CharacterItemRecord value2(Integer value) {
        setCharacterId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CharacterItemRecord value3(Integer value) {
        setItemId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CharacterItemRecord values(Integer value1, Integer value2, Integer value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CharacterItemRecord
     */
    public CharacterItemRecord() {
        super(CharacterItem.CHARACTER_ITEM);
    }

    /**
     * Create a detached, initialised CharacterItemRecord
     */
    public CharacterItemRecord(Integer characterItemId, Integer characterId, Integer itemId) {
        super(CharacterItem.CHARACTER_ITEM);

        set(0, characterItemId);
        set(1, characterId);
        set(2, itemId);
    }
}
