/*
 * This file is generated by jOOQ.
*/
package com.sukitsuki.bot.jooq.game.tables.records;


import com.sukitsuki.bot.jooq.game.tables.CharacterParty;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CharacterPartyRecord extends UpdatableRecordImpl<CharacterPartyRecord> implements Record4<Integer, Integer, Integer, Boolean> {

    private static final long serialVersionUID = -845905401;

    /**
     * Setter for <code>game.character_party.character_party_id</code>.
     */
    public void setCharacterPartyId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>game.character_party.character_party_id</code>.
     */
    public Integer getCharacterPartyId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>game.character_party.character_id</code>.
     */
    public void setCharacterId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>game.character_party.character_id</code>.
     */
    public Integer getCharacterId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>game.character_party.party_id</code>.
     */
    public void setPartyId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>game.character_party.party_id</code>.
     */
    public Integer getPartyId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>game.character_party.party_leader</code>.
     */
    public void setPartyLeader(Boolean value) {
        set(3, value);
    }

    /**
     * Getter for <code>game.character_party.party_leader</code>.
     */
    public Boolean getPartyLeader() {
        return (Boolean) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Integer, Integer, Integer, Boolean> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Integer, Integer, Integer, Boolean> valuesRow() {
        return (Row4) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return CharacterParty.CHARACTER_PARTY.CHARACTER_PARTY_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return CharacterParty.CHARACTER_PARTY.CHARACTER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return CharacterParty.CHARACTER_PARTY.PARTY_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field4() {
        return CharacterParty.CHARACTER_PARTY.PARTY_LEADER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getCharacterPartyId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getCharacterId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getPartyId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value4() {
        return getPartyLeader();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CharacterPartyRecord value1(Integer value) {
        setCharacterPartyId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CharacterPartyRecord value2(Integer value) {
        setCharacterId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CharacterPartyRecord value3(Integer value) {
        setPartyId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CharacterPartyRecord value4(Boolean value) {
        setPartyLeader(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CharacterPartyRecord values(Integer value1, Integer value2, Integer value3, Boolean value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CharacterPartyRecord
     */
    public CharacterPartyRecord() {
        super(CharacterParty.CHARACTER_PARTY);
    }

    /**
     * Create a detached, initialised CharacterPartyRecord
     */
    public CharacterPartyRecord(Integer characterPartyId, Integer characterId, Integer partyId, Boolean partyLeader) {
        super(CharacterParty.CHARACTER_PARTY);

        set(0, characterPartyId);
        set(1, characterId);
        set(2, partyId);
        set(3, partyLeader);
    }
}
