/*
 * This file is generated by jOOQ.
*/
package com.sukitsuki.bot.jooq.game.tables.records;


import com.sukitsuki.bot.jooq.game.tables.CharacterTitle;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CharacterTitleRecord extends UpdatableRecordImpl<CharacterTitleRecord> implements Record3<Integer, Integer, Integer> {

    private static final long serialVersionUID = 1286501048;

    /**
     * Setter for <code>game.character_title.character_title_id</code>.
     */
    public void setCharacterTitleId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>game.character_title.character_title_id</code>.
     */
    public Integer getCharacterTitleId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>game.character_title.character_id</code>.
     */
    public void setCharacterId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>game.character_title.character_id</code>.
     */
    public Integer getCharacterId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>game.character_title.title_id</code>.
     */
    public void setTitleId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>game.character_title.title_id</code>.
     */
    public Integer getTitleId() {
        return (Integer) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Integer, Integer, Integer> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Integer, Integer, Integer> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return CharacterTitle.CHARACTER_TITLE.CHARACTER_TITLE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return CharacterTitle.CHARACTER_TITLE.CHARACTER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return CharacterTitle.CHARACTER_TITLE.TITLE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getCharacterTitleId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getCharacterId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getTitleId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CharacterTitleRecord value1(Integer value) {
        setCharacterTitleId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CharacterTitleRecord value2(Integer value) {
        setCharacterId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CharacterTitleRecord value3(Integer value) {
        setTitleId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CharacterTitleRecord values(Integer value1, Integer value2, Integer value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CharacterTitleRecord
     */
    public CharacterTitleRecord() {
        super(CharacterTitle.CHARACTER_TITLE);
    }

    /**
     * Create a detached, initialised CharacterTitleRecord
     */
    public CharacterTitleRecord(Integer characterTitleId, Integer characterId, Integer titleId) {
        super(CharacterTitle.CHARACTER_TITLE);

        set(0, characterTitleId);
        set(1, characterId);
        set(2, titleId);
    }
}
