/*
 * This file is generated by jOOQ.
*/
package com.sukitsuki.bot.jooq.game.tables.records;


import com.sukitsuki.bot.jooq.game.tables.CharacterFaction;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CharacterFactionRecord extends UpdatableRecordImpl<CharacterFactionRecord> implements Record3<Integer, Integer, Integer> {

    private static final long serialVersionUID = -101189764;

    /**
     * Setter for <code>game.character_faction.character_faction_id</code>.
     */
    public void setCharacterFactionId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>game.character_faction.character_faction_id</code>.
     */
    public Integer getCharacterFactionId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>game.character_faction.character_id</code>.
     */
    public void setCharacterId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>game.character_faction.character_id</code>.
     */
    public Integer getCharacterId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>game.character_faction.faction_id</code>.
     */
    public void setFactionId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>game.character_faction.faction_id</code>.
     */
    public Integer getFactionId() {
        return (Integer) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Integer, Integer, Integer> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Integer, Integer, Integer> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return CharacterFaction.CHARACTER_FACTION.CHARACTER_FACTION_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return CharacterFaction.CHARACTER_FACTION.CHARACTER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return CharacterFaction.CHARACTER_FACTION.FACTION_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getCharacterFactionId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getCharacterId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getFactionId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CharacterFactionRecord value1(Integer value) {
        setCharacterFactionId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CharacterFactionRecord value2(Integer value) {
        setCharacterId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CharacterFactionRecord value3(Integer value) {
        setFactionId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CharacterFactionRecord values(Integer value1, Integer value2, Integer value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CharacterFactionRecord
     */
    public CharacterFactionRecord() {
        super(CharacterFaction.CHARACTER_FACTION);
    }

    /**
     * Create a detached, initialised CharacterFactionRecord
     */
    public CharacterFactionRecord(Integer characterFactionId, Integer characterId, Integer factionId) {
        super(CharacterFaction.CHARACTER_FACTION);

        set(0, characterFactionId);
        set(1, characterId);
        set(2, factionId);
    }
}
