/*
 * This file is generated by jOOQ.
*/
package com.sukitsuki.bot.jooq.game.tables.records;


import com.sukitsuki.bot.jooq.game.tables.Entity;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EntityRecord extends UpdatableRecordImpl<EntityRecord> implements Record4<Integer, Integer, String, Short> {

    private static final long serialVersionUID = -1261031311;

    /**
     * Setter for <code>game.entity.entity_id</code>.
     */
    public void setEntityId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>game.entity.entity_id</code>.
     */
    public Integer getEntityId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>game.entity.entity_type_id</code>.
     */
    public void setEntityTypeId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>game.entity.entity_type_id</code>.
     */
    public Integer getEntityTypeId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>game.entity.name</code>.
     */
    public void setName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>game.entity.name</code>.
     */
    public String getName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>game.entity.level</code>.
     */
    public void setLevel(Short value) {
        set(3, value);
    }

    /**
     * Getter for <code>game.entity.level</code>.
     */
    public Short getLevel() {
        return (Short) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Integer, Integer, String, Short> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Integer, Integer, String, Short> valuesRow() {
        return (Row4) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Entity.ENTITY.ENTITY_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return Entity.ENTITY.ENTITY_TYPE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Entity.ENTITY.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Short> field4() {
        return Entity.ENTITY.LEVEL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getEntityId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getEntityTypeId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Short value4() {
        return getLevel();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EntityRecord value1(Integer value) {
        setEntityId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EntityRecord value2(Integer value) {
        setEntityTypeId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EntityRecord value3(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EntityRecord value4(Short value) {
        setLevel(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EntityRecord values(Integer value1, Integer value2, String value3, Short value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached EntityRecord
     */
    public EntityRecord() {
        super(Entity.ENTITY);
    }

    /**
     * Create a detached, initialised EntityRecord
     */
    public EntityRecord(Integer entityId, Integer entityTypeId, String name, Short level) {
        super(Entity.ENTITY);

        set(0, entityId);
        set(1, entityTypeId);
        set(2, name);
        set(3, level);
    }
}
