/*
 * This file is generated by jOOQ.
*/
package com.sukitsuki.bot.jooq.game.tables.records;


import com.sukitsuki.bot.jooq.game.tables.EntityLoot;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EntityLootRecord extends UpdatableRecordImpl<EntityLootRecord> implements Record3<Integer, Integer, Integer> {

    private static final long serialVersionUID = 1456445168;

    /**
     * Setter for <code>game.entity_loot.entity_loot_id</code>.
     */
    public void setEntityLootId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>game.entity_loot.entity_loot_id</code>.
     */
    public Integer getEntityLootId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>game.entity_loot.loot_id</code>.
     */
    public void setLootId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>game.entity_loot.loot_id</code>.
     */
    public Integer getLootId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>game.entity_loot.entity_id</code>.
     */
    public void setEntityId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>game.entity_loot.entity_id</code>.
     */
    public Integer getEntityId() {
        return (Integer) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Integer, Integer, Integer> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Integer, Integer, Integer> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return EntityLoot.ENTITY_LOOT.ENTITY_LOOT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return EntityLoot.ENTITY_LOOT.LOOT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return EntityLoot.ENTITY_LOOT.ENTITY_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getEntityLootId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getLootId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getEntityId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EntityLootRecord value1(Integer value) {
        setEntityLootId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EntityLootRecord value2(Integer value) {
        setLootId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EntityLootRecord value3(Integer value) {
        setEntityId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EntityLootRecord values(Integer value1, Integer value2, Integer value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached EntityLootRecord
     */
    public EntityLootRecord() {
        super(EntityLoot.ENTITY_LOOT);
    }

    /**
     * Create a detached, initialised EntityLootRecord
     */
    public EntityLootRecord(Integer entityLootId, Integer lootId, Integer entityId) {
        super(EntityLoot.ENTITY_LOOT);

        set(0, entityLootId);
        set(1, lootId);
        set(2, entityId);
    }
}
