/*
 * This file is generated by jOOQ.
*/
package com.sukitsuki.bot.jooq.game.tables.records;


import com.sukitsuki.bot.jooq.game.tables.EntityLocation;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EntityLocationRecord extends UpdatableRecordImpl<EntityLocationRecord> implements Record3<Integer, Integer, Integer> {

    private static final long serialVersionUID = 179010265;

    /**
     * Setter for <code>game.entity_location.entity_location_id</code>.
     */
    public void setEntityLocationId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>game.entity_location.entity_location_id</code>.
     */
    public Integer getEntityLocationId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>game.entity_location.entity_id</code>.
     */
    public void setEntityId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>game.entity_location.entity_id</code>.
     */
    public Integer getEntityId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>game.entity_location.location_id</code>.
     */
    public void setLocationId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>game.entity_location.location_id</code>.
     */
    public Integer getLocationId() {
        return (Integer) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Integer, Integer, Integer> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Integer, Integer, Integer> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return EntityLocation.ENTITY_LOCATION.ENTITY_LOCATION_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return EntityLocation.ENTITY_LOCATION.ENTITY_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return EntityLocation.ENTITY_LOCATION.LOCATION_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getEntityLocationId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getEntityId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getLocationId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EntityLocationRecord value1(Integer value) {
        setEntityLocationId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EntityLocationRecord value2(Integer value) {
        setEntityId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EntityLocationRecord value3(Integer value) {
        setLocationId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EntityLocationRecord values(Integer value1, Integer value2, Integer value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached EntityLocationRecord
     */
    public EntityLocationRecord() {
        super(EntityLocation.ENTITY_LOCATION);
    }

    /**
     * Create a detached, initialised EntityLocationRecord
     */
    public EntityLocationRecord(Integer entityLocationId, Integer entityId, Integer locationId) {
        super(EntityLocation.ENTITY_LOCATION);

        set(0, entityLocationId);
        set(1, entityId);
        set(2, locationId);
    }
}
