/*
 * This file is generated by jOOQ.
*/
package com.sukitsuki.bot.jooq.game.tables.records;


import com.sukitsuki.bot.jooq.game.tables.EntityFaction;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EntityFactionRecord extends UpdatableRecordImpl<EntityFactionRecord> implements Record3<Integer, Integer, Integer> {

    private static final long serialVersionUID = -2078218598;

    /**
     * Setter for <code>game.entity_faction.entity_faction_id</code>.
     */
    public void setEntityFactionId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>game.entity_faction.entity_faction_id</code>.
     */
    public Integer getEntityFactionId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>game.entity_faction.entity_id</code>.
     */
    public void setEntityId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>game.entity_faction.entity_id</code>.
     */
    public Integer getEntityId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>game.entity_faction.faction_id</code>.
     */
    public void setFactionId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>game.entity_faction.faction_id</code>.
     */
    public Integer getFactionId() {
        return (Integer) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Integer, Integer, Integer> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Integer, Integer, Integer> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return EntityFaction.ENTITY_FACTION.ENTITY_FACTION_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return EntityFaction.ENTITY_FACTION.ENTITY_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return EntityFaction.ENTITY_FACTION.FACTION_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getEntityFactionId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getEntityId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getFactionId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EntityFactionRecord value1(Integer value) {
        setEntityFactionId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EntityFactionRecord value2(Integer value) {
        setEntityId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EntityFactionRecord value3(Integer value) {
        setFactionId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EntityFactionRecord values(Integer value1, Integer value2, Integer value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached EntityFactionRecord
     */
    public EntityFactionRecord() {
        super(EntityFaction.ENTITY_FACTION);
    }

    /**
     * Create a detached, initialised EntityFactionRecord
     */
    public EntityFactionRecord(Integer entityFactionId, Integer entityId, Integer factionId) {
        super(EntityFaction.ENTITY_FACTION);

        set(0, entityFactionId);
        set(1, entityId);
        set(2, factionId);
    }
}
