/*
 * This file is generated by jOOQ.
*/
package com.sukitsuki.bot.jooq.game.tables.records;


import com.sukitsuki.bot.jooq.game.tables.EntityStatusEffect;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EntityStatusEffectRecord extends UpdatableRecordImpl<EntityStatusEffectRecord> implements Record4<Integer, Integer, Integer, Timestamp> {

    private static final long serialVersionUID = -1358371107;

    /**
     * Setter for <code>game.entity_status_effect.entity_status_effect_id</code>.
     */
    public void setEntityStatusEffectId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>game.entity_status_effect.entity_status_effect_id</code>.
     */
    public Integer getEntityStatusEffectId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>game.entity_status_effect.entity_id</code>.
     */
    public void setEntityId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>game.entity_status_effect.entity_id</code>.
     */
    public Integer getEntityId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>game.entity_status_effect.status_effect_id</code>.
     */
    public void setStatusEffectId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>game.entity_status_effect.status_effect_id</code>.
     */
    public Integer getStatusEffectId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>game.entity_status_effect.date</code>.
     */
    public void setDate(Timestamp value) {
        set(3, value);
    }

    /**
     * Getter for <code>game.entity_status_effect.date</code>.
     */
    public Timestamp getDate() {
        return (Timestamp) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Integer, Integer, Integer, Timestamp> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Integer, Integer, Integer, Timestamp> valuesRow() {
        return (Row4) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return EntityStatusEffect.ENTITY_STATUS_EFFECT.ENTITY_STATUS_EFFECT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return EntityStatusEffect.ENTITY_STATUS_EFFECT.ENTITY_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return EntityStatusEffect.ENTITY_STATUS_EFFECT.STATUS_EFFECT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field4() {
        return EntityStatusEffect.ENTITY_STATUS_EFFECT.DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getEntityStatusEffectId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getEntityId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getStatusEffectId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value4() {
        return getDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EntityStatusEffectRecord value1(Integer value) {
        setEntityStatusEffectId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EntityStatusEffectRecord value2(Integer value) {
        setEntityId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EntityStatusEffectRecord value3(Integer value) {
        setStatusEffectId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EntityStatusEffectRecord value4(Timestamp value) {
        setDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EntityStatusEffectRecord values(Integer value1, Integer value2, Integer value3, Timestamp value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached EntityStatusEffectRecord
     */
    public EntityStatusEffectRecord() {
        super(EntityStatusEffect.ENTITY_STATUS_EFFECT);
    }

    /**
     * Create a detached, initialised EntityStatusEffectRecord
     */
    public EntityStatusEffectRecord(Integer entityStatusEffectId, Integer entityId, Integer statusEffectId, Timestamp date) {
        super(EntityStatusEffect.ENTITY_STATUS_EFFECT);

        set(0, entityStatusEffectId);
        set(1, entityId);
        set(2, statusEffectId);
        set(3, date);
    }
}
