/*
 * This file is generated by jOOQ.
*/
package com.sukitsuki.bot.jooq.game.tables.records;


import com.sukitsuki.bot.jooq.game.tables.GuildRank;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GuildRankRecord extends UpdatableRecordImpl<GuildRankRecord> implements Record3<Integer, Integer, Integer> {

    private static final long serialVersionUID = 183348474;

    /**
     * Setter for <code>game.guild_rank.guild_rank_id</code>.
     */
    public void setGuildRankId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>game.guild_rank.guild_rank_id</code>.
     */
    public Integer getGuildRankId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>game.guild_rank.guild_id</code>.
     */
    public void setGuildId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>game.guild_rank.guild_id</code>.
     */
    public Integer getGuildId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>game.guild_rank.rank_id</code>.
     */
    public void setRankId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>game.guild_rank.rank_id</code>.
     */
    public Integer getRankId() {
        return (Integer) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Integer, Integer, Integer> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Integer, Integer, Integer> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return GuildRank.GUILD_RANK.GUILD_RANK_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return GuildRank.GUILD_RANK.GUILD_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return GuildRank.GUILD_RANK.RANK_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getGuildRankId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getGuildId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getRankId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GuildRankRecord value1(Integer value) {
        setGuildRankId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GuildRankRecord value2(Integer value) {
        setGuildId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GuildRankRecord value3(Integer value) {
        setRankId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GuildRankRecord values(Integer value1, Integer value2, Integer value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached GuildRankRecord
     */
    public GuildRankRecord() {
        super(GuildRank.GUILD_RANK);
    }

    /**
     * Create a detached, initialised GuildRankRecord
     */
    public GuildRankRecord(Integer guildRankId, Integer guildId, Integer rankId) {
        super(GuildRank.GUILD_RANK);

        set(0, guildRankId);
        set(1, guildId);
        set(2, rankId);
    }
}
