/*
 * This file is generated by jOOQ.
*/
package com.sukitsuki.bot.jooq.game.tables.records;


import com.sukitsuki.bot.jooq.game.tables.ItemType;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ItemTypeRecord extends UpdatableRecordImpl<ItemTypeRecord> implements Record3<Integer, String, String> {

    private static final long serialVersionUID = 835991421;

    /**
     * Setter for <code>game.item_type.item_type_id</code>.
     */
    public void setItemTypeId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>game.item_type.item_type_id</code>.
     */
    public Integer getItemTypeId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>game.item_type.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>game.item_type.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>game.item_type.desc</code>.
     */
    public void setDesc(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>game.item_type.desc</code>.
     */
    public String getDesc() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Integer, String, String> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Integer, String, String> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return ItemType.ITEM_TYPE.ITEM_TYPE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return ItemType.ITEM_TYPE.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return ItemType.ITEM_TYPE.DESC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getItemTypeId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getDesc();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ItemTypeRecord value1(Integer value) {
        setItemTypeId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ItemTypeRecord value2(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ItemTypeRecord value3(String value) {
        setDesc(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ItemTypeRecord values(Integer value1, String value2, String value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ItemTypeRecord
     */
    public ItemTypeRecord() {
        super(ItemType.ITEM_TYPE);
    }

    /**
     * Create a detached, initialised ItemTypeRecord
     */
    public ItemTypeRecord(Integer itemTypeId, String name, String desc) {
        super(ItemType.ITEM_TYPE);

        set(0, itemTypeId);
        set(1, name);
        set(2, desc);
    }
}
