/*
 * This file is generated by jOOQ.
*/
package com.sukitsuki.bot.jooq.game.tables.records;


import com.sukitsuki.bot.jooq.game.tables.Item;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ItemRecord extends UpdatableRecordImpl<ItemRecord> implements Record5<Integer, Integer, String, Short, Boolean> {

    private static final long serialVersionUID = -665130117;

    /**
     * Setter for <code>game.item.item_id</code>.
     */
    public void setItemId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>game.item.item_id</code>.
     */
    public Integer getItemId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>game.item.item_type_id</code>.
     */
    public void setItemTypeId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>game.item.item_type_id</code>.
     */
    public Integer getItemTypeId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>game.item.name</code>.
     */
    public void setName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>game.item.name</code>.
     */
    public String getName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>game.item.required_level</code>.
     */
    public void setRequiredLevel(Short value) {
        set(3, value);
    }

    /**
     * Getter for <code>game.item.required_level</code>.
     */
    public Short getRequiredLevel() {
        return (Short) get(3);
    }

    /**
     * Setter for <code>game.item.durability</code>.
     */
    public void setDurability(Boolean value) {
        set(4, value);
    }

    /**
     * Getter for <code>game.item.durability</code>.
     */
    public Boolean getDurability() {
        return (Boolean) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Integer, Integer, String, Short, Boolean> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Integer, Integer, String, Short, Boolean> valuesRow() {
        return (Row5) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Item.ITEM.ITEM_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return Item.ITEM.ITEM_TYPE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Item.ITEM.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Short> field4() {
        return Item.ITEM.REQUIRED_LEVEL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field5() {
        return Item.ITEM.DURABILITY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getItemId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getItemTypeId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Short value4() {
        return getRequiredLevel();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value5() {
        return getDurability();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ItemRecord value1(Integer value) {
        setItemId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ItemRecord value2(Integer value) {
        setItemTypeId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ItemRecord value3(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ItemRecord value4(Short value) {
        setRequiredLevel(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ItemRecord value5(Boolean value) {
        setDurability(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ItemRecord values(Integer value1, Integer value2, String value3, Short value4, Boolean value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ItemRecord
     */
    public ItemRecord() {
        super(Item.ITEM);
    }

    /**
     * Create a detached, initialised ItemRecord
     */
    public ItemRecord(Integer itemId, Integer itemTypeId, String name, Short requiredLevel, Boolean durability) {
        super(Item.ITEM);

        set(0, itemId);
        set(1, itemTypeId);
        set(2, name);
        set(3, requiredLevel);
        set(4, durability);
    }
}
