/*
 * This file is generated by jOOQ.
*/
package com.sukitsuki.bot.jooq.game.tables.records;


import com.sukitsuki.bot.jooq.game.tables.ItemLocation;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ItemLocationRecord extends UpdatableRecordImpl<ItemLocationRecord> implements Record3<Integer, Integer, Integer> {

    private static final long serialVersionUID = -1619875895;

    /**
     * Setter for <code>game.item_location.item_location_id</code>.
     */
    public void setItemLocationId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>game.item_location.item_location_id</code>.
     */
    public Integer getItemLocationId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>game.item_location.item_id</code>.
     */
    public void setItemId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>game.item_location.item_id</code>.
     */
    public Integer getItemId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>game.item_location.location_id</code>.
     */
    public void setLocationId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>game.item_location.location_id</code>.
     */
    public Integer getLocationId() {
        return (Integer) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Integer, Integer, Integer> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Integer, Integer, Integer> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return ItemLocation.ITEM_LOCATION.ITEM_LOCATION_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return ItemLocation.ITEM_LOCATION.ITEM_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return ItemLocation.ITEM_LOCATION.LOCATION_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getItemLocationId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getItemId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getLocationId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ItemLocationRecord value1(Integer value) {
        setItemLocationId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ItemLocationRecord value2(Integer value) {
        setItemId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ItemLocationRecord value3(Integer value) {
        setLocationId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ItemLocationRecord values(Integer value1, Integer value2, Integer value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ItemLocationRecord
     */
    public ItemLocationRecord() {
        super(ItemLocation.ITEM_LOCATION);
    }

    /**
     * Create a detached, initialised ItemLocationRecord
     */
    public ItemLocationRecord(Integer itemLocationId, Integer itemId, Integer locationId) {
        super(ItemLocation.ITEM_LOCATION);

        set(0, itemLocationId);
        set(1, itemId);
        set(2, locationId);
    }
}
