/*
 * This file is generated by jOOQ.
*/
package com.sukitsuki.bot.jooq.game.tables.records;


import com.sukitsuki.bot.jooq.game.tables.ItemLoot;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ItemLootRecord extends UpdatableRecordImpl<ItemLootRecord> implements Record4<Integer, Integer, Integer, Float> {

    private static final long serialVersionUID = -2106276889;

    /**
     * Setter for <code>game.item_loot.item_loot_id</code>.
     */
    public void setItemLootId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>game.item_loot.item_loot_id</code>.
     */
    public Integer getItemLootId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>game.item_loot.loot_id</code>.
     */
    public void setLootId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>game.item_loot.loot_id</code>.
     */
    public Integer getLootId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>game.item_loot.item_id</code>.
     */
    public void setItemId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>game.item_loot.item_id</code>.
     */
    public Integer getItemId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>game.item_loot.drop_chance</code>.
     */
    public void setDropChance(Float value) {
        set(3, value);
    }

    /**
     * Getter for <code>game.item_loot.drop_chance</code>.
     */
    public Float getDropChance() {
        return (Float) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Integer, Integer, Integer, Float> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Integer, Integer, Integer, Float> valuesRow() {
        return (Row4) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return ItemLoot.ITEM_LOOT.ITEM_LOOT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return ItemLoot.ITEM_LOOT.LOOT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return ItemLoot.ITEM_LOOT.ITEM_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Float> field4() {
        return ItemLoot.ITEM_LOOT.DROP_CHANCE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getItemLootId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getLootId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getItemId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Float value4() {
        return getDropChance();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ItemLootRecord value1(Integer value) {
        setItemLootId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ItemLootRecord value2(Integer value) {
        setLootId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ItemLootRecord value3(Integer value) {
        setItemId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ItemLootRecord value4(Float value) {
        setDropChance(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ItemLootRecord values(Integer value1, Integer value2, Integer value3, Float value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ItemLootRecord
     */
    public ItemLootRecord() {
        super(ItemLoot.ITEM_LOOT);
    }

    /**
     * Create a detached, initialised ItemLootRecord
     */
    public ItemLootRecord(Integer itemLootId, Integer lootId, Integer itemId, Float dropChance) {
        super(ItemLoot.ITEM_LOOT);

        set(0, itemLootId);
        set(1, lootId);
        set(2, itemId);
        set(3, dropChance);
    }
}
