/*
 * This file is generated by jOOQ.
*/
package com.sukitsuki.bot.jooq.game.tables.records;


import com.sukitsuki.bot.jooq.game.tables.Location;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class LocationRecord extends UpdatableRecordImpl<LocationRecord> implements Record4<Integer, Long, Long, Integer> {

    private static final long serialVersionUID = -4279535;

    /**
     * Setter for <code>game.location.location_id</code>.
     */
    public void setLocationId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>game.location.location_id</code>.
     */
    public Integer getLocationId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>game.location.x</code>.
     */
    public void setX(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>game.location.x</code>.
     */
    public Long getX() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>game.location.y</code>.
     */
    public void setY(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>game.location.y</code>.
     */
    public Long getY() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>game.location.place_id</code>.
     */
    public void setPlaceId(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>game.location.place_id</code>.
     */
    public Integer getPlaceId() {
        return (Integer) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Integer, Long, Long, Integer> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Integer, Long, Long, Integer> valuesRow() {
        return (Row4) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Location.LOCATION.LOCATION_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field2() {
        return Location.LOCATION.X;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field3() {
        return Location.LOCATION.Y;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return Location.LOCATION.PLACE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getLocationId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value2() {
        return getX();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value3() {
        return getY();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getPlaceId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocationRecord value1(Integer value) {
        setLocationId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocationRecord value2(Long value) {
        setX(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocationRecord value3(Long value) {
        setY(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocationRecord value4(Integer value) {
        setPlaceId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocationRecord values(Integer value1, Long value2, Long value3, Integer value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached LocationRecord
     */
    public LocationRecord() {
        super(Location.LOCATION);
    }

    /**
     * Create a detached, initialised LocationRecord
     */
    public LocationRecord(Integer locationId, Long x, Long y, Integer placeId) {
        super(Location.LOCATION);

        set(0, locationId);
        set(1, x);
        set(2, y);
        set(3, placeId);
    }
}
