/*
 * This file is generated by jOOQ.
*/
package com.sukitsuki.bot.jooq.game.tables.records;


import com.sukitsuki.bot.jooq.game.tables.Loot;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class LootRecord extends UpdatableRecordImpl<LootRecord> implements Record3<Integer, Long, Long> {

    private static final long serialVersionUID = -1474735263;

    /**
     * Setter for <code>game.loot.loot_id</code>.
     */
    public void setLootId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>game.loot.loot_id</code>.
     */
    public Integer getLootId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>game.loot.xp</code>.
     */
    public void setXp(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>game.loot.xp</code>.
     */
    public Long getXp() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>game.loot.money</code>.
     */
    public void setMoney(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>game.loot.money</code>.
     */
    public Long getMoney() {
        return (Long) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Integer, Long, Long> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Integer, Long, Long> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Loot.LOOT.LOOT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field2() {
        return Loot.LOOT.XP;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field3() {
        return Loot.LOOT.MONEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getLootId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value2() {
        return getXp();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value3() {
        return getMoney();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LootRecord value1(Integer value) {
        setLootId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LootRecord value2(Long value) {
        setXp(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LootRecord value3(Long value) {
        setMoney(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LootRecord values(Integer value1, Long value2, Long value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached LootRecord
     */
    public LootRecord() {
        super(Loot.LOOT);
    }

    /**
     * Create a detached, initialised LootRecord
     */
    public LootRecord(Integer lootId, Long xp, Long money) {
        super(Loot.LOOT);

        set(0, lootId);
        set(1, xp);
        set(2, money);
    }
}
