/*
 * This file is generated by jOOQ.
*/
package com.sukitsuki.bot.jooq.game.tables.records;


import com.sukitsuki.bot.jooq.game.tables.StatusEffect;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class StatusEffectRecord extends UpdatableRecordImpl<StatusEffectRecord> implements Record5<Integer, String, Integer, Long, String> {

    private static final long serialVersionUID = 1578325326;

    /**
     * Setter for <code>game.status_effect.status_effect_id</code>.
     */
    public void setStatusEffectId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>game.status_effect.status_effect_id</code>.
     */
    public Integer getStatusEffectId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>game.status_effect.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>game.status_effect.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>game.status_effect.effect_type_id</code>.
     */
    public void setEffectTypeId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>game.status_effect.effect_type_id</code>.
     */
    public Integer getEffectTypeId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>game.status_effect.duration</code>.
     */
    public void setDuration(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>game.status_effect.duration</code>.
     */
    public Long getDuration() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>game.status_effect.desc</code>.
     */
    public void setDesc(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>game.status_effect.desc</code>.
     */
    public String getDesc() {
        return (String) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Integer, String, Integer, Long, String> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Integer, String, Integer, Long, String> valuesRow() {
        return (Row5) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return StatusEffect.STATUS_EFFECT.STATUS_EFFECT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return StatusEffect.STATUS_EFFECT.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return StatusEffect.STATUS_EFFECT.EFFECT_TYPE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field4() {
        return StatusEffect.STATUS_EFFECT.DURATION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return StatusEffect.STATUS_EFFECT.DESC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getStatusEffectId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getEffectTypeId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value4() {
        return getDuration();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getDesc();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StatusEffectRecord value1(Integer value) {
        setStatusEffectId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StatusEffectRecord value2(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StatusEffectRecord value3(Integer value) {
        setEffectTypeId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StatusEffectRecord value4(Long value) {
        setDuration(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StatusEffectRecord value5(String value) {
        setDesc(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StatusEffectRecord values(Integer value1, String value2, Integer value3, Long value4, String value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached StatusEffectRecord
     */
    public StatusEffectRecord() {
        super(StatusEffect.STATUS_EFFECT);
    }

    /**
     * Create a detached, initialised StatusEffectRecord
     */
    public StatusEffectRecord(Integer statusEffectId, String name, Integer effectTypeId, Long duration, String desc) {
        super(StatusEffect.STATUS_EFFECT);

        set(0, statusEffectId);
        set(1, name);
        set(2, effectTypeId);
        set(3, duration);
        set(4, desc);
    }
}
