/*
 * This file is generated by jOOQ.
*/
package com.sukitsuki.bot.jooq.game.tables.records;


import com.sukitsuki.bot.jooq.game.tables.User;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record11;
import org.jooq.Row11;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserRecord extends UpdatableRecordImpl<UserRecord> implements Record11<Integer, Integer, Integer, Integer, Integer, Integer, Integer, Integer, Integer, Integer, Integer> {

    private static final long serialVersionUID = 1222377714;

    /**
     * Setter for <code>game.User.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>game.User.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>game.User.exp</code>.
     */
    public void setExp(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>game.User.exp</code>.
     */
    public Integer getExp() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>game.User.level</code>.
     */
    public void setLevel(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>game.User.level</code>.
     */
    public Integer getLevel() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>game.User.attack</code>.
     */
    public void setAttack(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>game.User.attack</code>.
     */
    public Integer getAttack() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>game.User.defence</code>.
     */
    public void setDefence(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>game.User.defence</code>.
     */
    public Integer getDefence() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>game.User.faction</code>.
     */
    public void setFaction(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>game.User.faction</code>.
     */
    public Integer getFaction() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>game.User.location</code>.
     */
    public void setLocation(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>game.User.location</code>.
     */
    public Integer getLocation() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>game.User.hp</code>.
     */
    public void setHp(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>game.User.hp</code>.
     */
    public Integer getHp() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>game.User.mp</code>.
     */
    public void setMp(Integer value) {
        set(8, value);
    }

    /**
     * Getter for <code>game.User.mp</code>.
     */
    public Integer getMp() {
        return (Integer) get(8);
    }

    /**
     * Setter for <code>game.User.hp_max</code>.
     */
    public void setHpMax(Integer value) {
        set(9, value);
    }

    /**
     * Getter for <code>game.User.hp_max</code>.
     */
    public Integer getHpMax() {
        return (Integer) get(9);
    }

    /**
     * Setter for <code>game.User.mp_max</code>.
     */
    public void setMpMax(Integer value) {
        set(10, value);
    }

    /**
     * Getter for <code>game.User.mp_max</code>.
     */
    public Integer getMpMax() {
        return (Integer) get(10);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record11 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row11<Integer, Integer, Integer, Integer, Integer, Integer, Integer, Integer, Integer, Integer, Integer> fieldsRow() {
        return (Row11) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row11<Integer, Integer, Integer, Integer, Integer, Integer, Integer, Integer, Integer, Integer, Integer> valuesRow() {
        return (Row11) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return User.USER.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return User.USER.EXP;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return User.USER.LEVEL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return User.USER.ATTACK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field5() {
        return User.USER.DEFENCE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field6() {
        return User.USER.FACTION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field7() {
        return User.USER.LOCATION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field8() {
        return User.USER.HP;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field9() {
        return User.USER.MP;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field10() {
        return User.USER.HP_MAX;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field11() {
        return User.USER.MP_MAX;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getExp();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getLevel();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getAttack();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value5() {
        return getDefence();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value6() {
        return getFaction();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value7() {
        return getLocation();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value8() {
        return getHp();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value9() {
        return getMp();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value10() {
        return getHpMax();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value11() {
        return getMpMax();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserRecord value2(Integer value) {
        setExp(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserRecord value3(Integer value) {
        setLevel(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserRecord value4(Integer value) {
        setAttack(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserRecord value5(Integer value) {
        setDefence(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserRecord value6(Integer value) {
        setFaction(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserRecord value7(Integer value) {
        setLocation(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserRecord value8(Integer value) {
        setHp(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserRecord value9(Integer value) {
        setMp(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserRecord value10(Integer value) {
        setHpMax(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserRecord value11(Integer value) {
        setMpMax(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserRecord values(Integer value1, Integer value2, Integer value3, Integer value4, Integer value5, Integer value6, Integer value7, Integer value8, Integer value9, Integer value10, Integer value11) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UserRecord
     */
    public UserRecord() {
        super(User.USER);
    }

    /**
     * Create a detached, initialised UserRecord
     */
    public UserRecord(Integer id, Integer exp, Integer level, Integer attack, Integer defence, Integer faction, Integer location, Integer hp, Integer mp, Integer hpMax, Integer mpMax) {
        super(User.USER);

        set(0, id);
        set(1, exp);
        set(2, level);
        set(3, attack);
        set(4, defence);
        set(5, faction);
        set(6, location);
        set(7, hp);
        set(8, mp);
        set(9, hpMax);
        set(10, mpMax);
    }
}
