/*
 * This file is generated by jOOQ.
*/
package com.sukitsuki.bot.jooq.game.tables;


import com.sukitsuki.bot.jooq.game.Game;
import com.sukitsuki.bot.jooq.game.Keys;
import com.sukitsuki.bot.jooq.game.tables.records.AbilityRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Ability extends TableImpl<AbilityRecord> {

    private static final long serialVersionUID = 1845623943;

    /**
     * The reference instance of <code>game.ability</code>
     */
    public static final Ability ABILITY = new Ability();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AbilityRecord> getRecordType() {
        return AbilityRecord.class;
    }

    /**
     * The column <code>game.ability.ability_id</code>.
     */
    public final TableField<AbilityRecord, Integer> ABILITY_ID = createField("ability_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>game.ability.name</code>.
     */
    public final TableField<AbilityRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(510).nullable(false), this, "");

    /**
     * The column <code>game.ability.ability_type_id</code>.
     */
    public final TableField<AbilityRecord, Integer> ABILITY_TYPE_ID = createField("ability_type_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>game.ability.required_level</code>.
     */
    public final TableField<AbilityRecord, Short> REQUIRED_LEVEL = createField("required_level", org.jooq.impl.SQLDataType.SMALLINT, this, "");

    /**
     * Create a <code>game.ability</code> table reference
     */
    public Ability() {
        this("ability", null);
    }

    /**
     * Create an aliased <code>game.ability</code> table reference
     */
    public Ability(String alias) {
        this(alias, ABILITY);
    }

    private Ability(String alias, Table<AbilityRecord> aliased) {
        this(alias, aliased, null);
    }

    private Ability(String alias, Table<AbilityRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Game.GAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<AbilityRecord> getPrimaryKey() {
        return Keys.ABILITY_PKEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<AbilityRecord>> getKeys() {
        return Arrays.<UniqueKey<AbilityRecord>>asList(Keys.ABILITY_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<AbilityRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<AbilityRecord, ?>>asList(Keys.ABILITY__FK_ABILITY_ABILITY_TYPE_ID);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Ability as(String alias) {
        return new Ability(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Ability rename(String name) {
        return new Ability(name, null);
    }
}
