/*
 * This file is generated by jOOQ.
*/
package com.sukitsuki.bot.jooq.game.tables;


import com.sukitsuki.bot.jooq.game.Game;
import com.sukitsuki.bot.jooq.game.Keys;
import com.sukitsuki.bot.jooq.game.tables.records.AbilityTypeRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AbilityType extends TableImpl<AbilityTypeRecord> {

    private static final long serialVersionUID = -1140165416;

    /**
     * The reference instance of <code>game.ability_type</code>
     */
    public static final AbilityType ABILITY_TYPE = new AbilityType();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AbilityTypeRecord> getRecordType() {
        return AbilityTypeRecord.class;
    }

    /**
     * The column <code>game.ability_type.ability_type_id</code>.
     */
    public final TableField<AbilityTypeRecord, Integer> ABILITY_TYPE_ID = createField("ability_type_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>game.ability_type.name</code>.
     */
    public final TableField<AbilityTypeRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(510).nullable(false), this, "");

    /**
     * The column <code>game.ability_type.desc</code>.
     */
    public final TableField<AbilityTypeRecord, String> DESC = createField("desc", org.jooq.impl.SQLDataType.VARCHAR.length(510).defaultValue(org.jooq.impl.DSL.field("NULL::character varying", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * Create a <code>game.ability_type</code> table reference
     */
    public AbilityType() {
        this("ability_type", null);
    }

    /**
     * Create an aliased <code>game.ability_type</code> table reference
     */
    public AbilityType(String alias) {
        this(alias, ABILITY_TYPE);
    }

    private AbilityType(String alias, Table<AbilityTypeRecord> aliased) {
        this(alias, aliased, null);
    }

    private AbilityType(String alias, Table<AbilityTypeRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Game.GAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<AbilityTypeRecord> getPrimaryKey() {
        return Keys.ABILITY_TYPE_PKEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<AbilityTypeRecord>> getKeys() {
        return Arrays.<UniqueKey<AbilityTypeRecord>>asList(Keys.ABILITY_TYPE_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AbilityType as(String alias) {
        return new AbilityType(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public AbilityType rename(String name) {
        return new AbilityType(name, null);
    }
}
