/*
 * This file is generated by jOOQ.
*/
package com.sukitsuki.bot.jooq.game.tables;


import com.sukitsuki.bot.jooq.game.Game;
import com.sukitsuki.bot.jooq.game.Keys;
import com.sukitsuki.bot.jooq.game.tables.records.AttributeRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Attribute extends TableImpl<AttributeRecord> {

    private static final long serialVersionUID = -1080318350;

    /**
     * The reference instance of <code>game.attribute</code>
     */
    public static final Attribute ATTRIBUTE = new Attribute();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AttributeRecord> getRecordType() {
        return AttributeRecord.class;
    }

    /**
     * The column <code>game.attribute.attribute_id</code>.
     */
    public final TableField<AttributeRecord, Integer> ATTRIBUTE_ID = createField("attribute_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>game.attribute.name</code>.
     */
    public final TableField<AttributeRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(510).nullable(false), this, "");

    /**
     * The column <code>game.attribute.desc</code>.
     */
    public final TableField<AttributeRecord, String> DESC = createField("desc", org.jooq.impl.SQLDataType.VARCHAR.length(510).defaultValue(org.jooq.impl.DSL.field("NULL::character varying", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * Create a <code>game.attribute</code> table reference
     */
    public Attribute() {
        this("attribute", null);
    }

    /**
     * Create an aliased <code>game.attribute</code> table reference
     */
    public Attribute(String alias) {
        this(alias, ATTRIBUTE);
    }

    private Attribute(String alias, Table<AttributeRecord> aliased) {
        this(alias, aliased, null);
    }

    private Attribute(String alias, Table<AttributeRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Game.GAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<AttributeRecord> getPrimaryKey() {
        return Keys.ATTRIBUTE_PKEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<AttributeRecord>> getKeys() {
        return Arrays.<UniqueKey<AttributeRecord>>asList(Keys.ATTRIBUTE_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Attribute as(String alias) {
        return new Attribute(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Attribute rename(String name) {
        return new Attribute(name, null);
    }
}
