/*
 * This file is generated by jOOQ.
*/
package com.sukitsuki.bot.jooq.game.tables;


import com.sukitsuki.bot.jooq.game.Game;
import com.sukitsuki.bot.jooq.game.Keys;
import com.sukitsuki.bot.jooq.game.tables.records.CharacterTitleRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CharacterTitle extends TableImpl<CharacterTitleRecord> {

    private static final long serialVersionUID = 1543144201;

    /**
     * The reference instance of <code>game.character_title</code>
     */
    public static final CharacterTitle CHARACTER_TITLE = new CharacterTitle();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<CharacterTitleRecord> getRecordType() {
        return CharacterTitleRecord.class;
    }

    /**
     * The column <code>game.character_title.character_title_id</code>.
     */
    public final TableField<CharacterTitleRecord, Integer> CHARACTER_TITLE_ID = createField("character_title_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>game.character_title.character_id</code>.
     */
    public final TableField<CharacterTitleRecord, Integer> CHARACTER_ID = createField("character_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>game.character_title.title_id</code>.
     */
    public final TableField<CharacterTitleRecord, Integer> TITLE_ID = createField("title_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * Create a <code>game.character_title</code> table reference
     */
    public CharacterTitle() {
        this("character_title", null);
    }

    /**
     * Create an aliased <code>game.character_title</code> table reference
     */
    public CharacterTitle(String alias) {
        this(alias, CHARACTER_TITLE);
    }

    private CharacterTitle(String alias, Table<CharacterTitleRecord> aliased) {
        this(alias, aliased, null);
    }

    private CharacterTitle(String alias, Table<CharacterTitleRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Game.GAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<CharacterTitleRecord> getPrimaryKey() {
        return Keys.CHARACTER_TITLE_PKEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<CharacterTitleRecord>> getKeys() {
        return Arrays.<UniqueKey<CharacterTitleRecord>>asList(Keys.CHARACTER_TITLE_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<CharacterTitleRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<CharacterTitleRecord, ?>>asList(Keys.CHARACTER_TITLE__FK_CHARACTER_TITLE_CHARACTER_ID, Keys.CHARACTER_TITLE__FK_CHARACTER_TITLE_TITLE_ID);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CharacterTitle as(String alias) {
        return new CharacterTitle(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public CharacterTitle rename(String name) {
        return new CharacterTitle(name, null);
    }
}
