/*
 * This file is generated by jOOQ.
*/
package com.sukitsuki.bot.jooq.game.tables;


import com.sukitsuki.bot.jooq.game.Game;
import com.sukitsuki.bot.jooq.game.Keys;
import com.sukitsuki.bot.jooq.game.tables.records.CharacterEquipmentRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CharacterEquipment extends TableImpl<CharacterEquipmentRecord> {

    private static final long serialVersionUID = -1699906112;

    /**
     * The reference instance of <code>game.character_equipment</code>
     */
    public static final CharacterEquipment CHARACTER_EQUIPMENT = new CharacterEquipment();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<CharacterEquipmentRecord> getRecordType() {
        return CharacterEquipmentRecord.class;
    }

    /**
     * The column <code>game.character_equipment.character_equipment_id</code>.
     */
    public final TableField<CharacterEquipmentRecord, Integer> CHARACTER_EQUIPMENT_ID = createField("character_equipment_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>game.character_equipment.equipment_slot_id</code>.
     */
    public final TableField<CharacterEquipmentRecord, Integer> EQUIPMENT_SLOT_ID = createField("equipment_slot_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>game.character_equipment.character_id</code>.
     */
    public final TableField<CharacterEquipmentRecord, Integer> CHARACTER_ID = createField("character_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>game.character_equipment.item_id</code>.
     */
    public final TableField<CharacterEquipmentRecord, Integer> ITEM_ID = createField("item_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * Create a <code>game.character_equipment</code> table reference
     */
    public CharacterEquipment() {
        this("character_equipment", null);
    }

    /**
     * Create an aliased <code>game.character_equipment</code> table reference
     */
    public CharacterEquipment(String alias) {
        this(alias, CHARACTER_EQUIPMENT);
    }

    private CharacterEquipment(String alias, Table<CharacterEquipmentRecord> aliased) {
        this(alias, aliased, null);
    }

    private CharacterEquipment(String alias, Table<CharacterEquipmentRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Game.GAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<CharacterEquipmentRecord> getPrimaryKey() {
        return Keys.CHARACTER_EQUIPMENT_PKEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<CharacterEquipmentRecord>> getKeys() {
        return Arrays.<UniqueKey<CharacterEquipmentRecord>>asList(Keys.CHARACTER_EQUIPMENT_PKEY, Keys.CHARACTER_EQUIPMENT_EQUIPMENT_SLOT_ID_CHARACTER_ID_KEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<CharacterEquipmentRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<CharacterEquipmentRecord, ?>>asList(Keys.CHARACTER_EQUIPMENT__FK_CHARACTER_EQUIPMENT_EQUIPMENT_SLOT_ID, Keys.CHARACTER_EQUIPMENT__FK_CHARACTER_EQUIPMENT_CHARACTER_ID, Keys.CHARACTER_EQUIPMENT__FK_CHARACTER_EQUIPMENT_ITEM_ID);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CharacterEquipment as(String alias) {
        return new CharacterEquipment(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public CharacterEquipment rename(String name) {
        return new CharacterEquipment(name, null);
    }
}
