/*
 * This file is generated by jOOQ.
*/
package com.sukitsuki.bot.jooq.game.tables;


import com.sukitsuki.bot.jooq.game.Game;
import com.sukitsuki.bot.jooq.game.Keys;
import com.sukitsuki.bot.jooq.game.tables.records.CharacterLootRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CharacterLoot extends TableImpl<CharacterLootRecord> {

    private static final long serialVersionUID = -509953079;

    /**
     * The reference instance of <code>game.character_loot</code>
     */
    public static final CharacterLoot CHARACTER_LOOT = new CharacterLoot();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<CharacterLootRecord> getRecordType() {
        return CharacterLootRecord.class;
    }

    /**
     * The column <code>game.character_loot.character_loot_id</code>.
     */
    public final TableField<CharacterLootRecord, Integer> CHARACTER_LOOT_ID = createField("character_loot_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>game.character_loot.loot_id</code>.
     */
    public final TableField<CharacterLootRecord, Integer> LOOT_ID = createField("loot_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>game.character_loot.character_id</code>.
     */
    public final TableField<CharacterLootRecord, Integer> CHARACTER_ID = createField("character_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * Create a <code>game.character_loot</code> table reference
     */
    public CharacterLoot() {
        this("character_loot", null);
    }

    /**
     * Create an aliased <code>game.character_loot</code> table reference
     */
    public CharacterLoot(String alias) {
        this(alias, CHARACTER_LOOT);
    }

    private CharacterLoot(String alias, Table<CharacterLootRecord> aliased) {
        this(alias, aliased, null);
    }

    private CharacterLoot(String alias, Table<CharacterLootRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Game.GAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<CharacterLootRecord> getPrimaryKey() {
        return Keys.CHARACTER_LOOT_PKEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<CharacterLootRecord>> getKeys() {
        return Arrays.<UniqueKey<CharacterLootRecord>>asList(Keys.CHARACTER_LOOT_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<CharacterLootRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<CharacterLootRecord, ?>>asList(Keys.CHARACTER_LOOT__FK_CHARACTER_LOOT_LOOT_ID, Keys.CHARACTER_LOOT__FK_CHARACTER_LOOT_CHARACTER_ID);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CharacterLoot as(String alias) {
        return new CharacterLoot(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public CharacterLoot rename(String name) {
        return new CharacterLoot(name, null);
    }
}
