/*
 * This file is generated by jOOQ.
*/
package com.sukitsuki.bot.jooq.game.tables;


import com.sukitsuki.bot.jooq.game.Game;
import com.sukitsuki.bot.jooq.game.Keys;
import com.sukitsuki.bot.jooq.game.tables.records.CharacterGuildRankRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CharacterGuildRank extends TableImpl<CharacterGuildRankRecord> {

    private static final long serialVersionUID = -1432754229;

    /**
     * The reference instance of <code>game.character_guild_rank</code>
     */
    public static final CharacterGuildRank CHARACTER_GUILD_RANK = new CharacterGuildRank();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<CharacterGuildRankRecord> getRecordType() {
        return CharacterGuildRankRecord.class;
    }

    /**
     * The column <code>game.character_guild_rank.character_guild_rank_id</code>.
     */
    public final TableField<CharacterGuildRankRecord, Integer> CHARACTER_GUILD_RANK_ID = createField("character_guild_rank_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>game.character_guild_rank.character_id</code>.
     */
    public final TableField<CharacterGuildRankRecord, Integer> CHARACTER_ID = createField("character_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>game.character_guild_rank.guild_rank_id</code>.
     */
    public final TableField<CharacterGuildRankRecord, Integer> GUILD_RANK_ID = createField("guild_rank_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * Create a <code>game.character_guild_rank</code> table reference
     */
    public CharacterGuildRank() {
        this("character_guild_rank", null);
    }

    /**
     * Create an aliased <code>game.character_guild_rank</code> table reference
     */
    public CharacterGuildRank(String alias) {
        this(alias, CHARACTER_GUILD_RANK);
    }

    private CharacterGuildRank(String alias, Table<CharacterGuildRankRecord> aliased) {
        this(alias, aliased, null);
    }

    private CharacterGuildRank(String alias, Table<CharacterGuildRankRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Game.GAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<CharacterGuildRankRecord> getPrimaryKey() {
        return Keys.CHARACTER_GUILD_RANK_PKEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<CharacterGuildRankRecord>> getKeys() {
        return Arrays.<UniqueKey<CharacterGuildRankRecord>>asList(Keys.CHARACTER_GUILD_RANK_PKEY, Keys.CHARACTER_GUILD_RANK_CHARACTER_ID_GUILD_RANK_ID_KEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<CharacterGuildRankRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<CharacterGuildRankRecord, ?>>asList(Keys.CHARACTER_GUILD_RANK__FK_CHARACTER_GUILD_RANK_CHARACTER_ID, Keys.CHARACTER_GUILD_RANK__FK_CHARACTER_GUILD_RANK_GUILD_RANK_ID);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CharacterGuildRank as(String alias) {
        return new CharacterGuildRank(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public CharacterGuildRank rename(String name) {
        return new CharacterGuildRank(name, null);
    }
}
