/*
 * This file is generated by jOOQ.
*/
package com.sukitsuki.bot.jooq.game.tables;


import com.sukitsuki.bot.jooq.game.Game;
import com.sukitsuki.bot.jooq.game.Keys;
import com.sukitsuki.bot.jooq.game.tables.records.CharacterTypeRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CharacterType extends TableImpl<CharacterTypeRecord> {

    private static final long serialVersionUID = -1167883798;

    /**
     * The reference instance of <code>game.character_type</code>
     */
    public static final CharacterType CHARACTER_TYPE = new CharacterType();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<CharacterTypeRecord> getRecordType() {
        return CharacterTypeRecord.class;
    }

    /**
     * The column <code>game.character_type.character_type_id</code>.
     */
    public final TableField<CharacterTypeRecord, Integer> CHARACTER_TYPE_ID = createField("character_type_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>game.character_type.name</code>.
     */
    public final TableField<CharacterTypeRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(510).nullable(false), this, "");

    /**
     * Create a <code>game.character_type</code> table reference
     */
    public CharacterType() {
        this("character_type", null);
    }

    /**
     * Create an aliased <code>game.character_type</code> table reference
     */
    public CharacterType(String alias) {
        this(alias, CHARACTER_TYPE);
    }

    private CharacterType(String alias, Table<CharacterTypeRecord> aliased) {
        this(alias, aliased, null);
    }

    private CharacterType(String alias, Table<CharacterTypeRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Game.GAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<CharacterTypeRecord> getPrimaryKey() {
        return Keys.CHARACTER_TYPE_PKEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<CharacterTypeRecord>> getKeys() {
        return Arrays.<UniqueKey<CharacterTypeRecord>>asList(Keys.CHARACTER_TYPE_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CharacterType as(String alias) {
        return new CharacterType(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public CharacterType rename(String name) {
        return new CharacterType(name, null);
    }
}
