/*
 * This file is generated by jOOQ.
*/
package com.sukitsuki.bot.jooq.game.tables;


import com.sukitsuki.bot.jooq.game.Game;
import com.sukitsuki.bot.jooq.game.Keys;
import com.sukitsuki.bot.jooq.game.tables.records.ClassAbilityRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ClassAbility extends TableImpl<ClassAbilityRecord> {

    private static final long serialVersionUID = -872680439;

    /**
     * The reference instance of <code>game.class_ability</code>
     */
    public static final ClassAbility CLASS_ABILITY = new ClassAbility();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ClassAbilityRecord> getRecordType() {
        return ClassAbilityRecord.class;
    }

    /**
     * The column <code>game.class_ability.class_ability_id</code>.
     */
    public final TableField<ClassAbilityRecord, Integer> CLASS_ABILITY_ID = createField("class_ability_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>game.class_ability.class_id</code>.
     */
    public final TableField<ClassAbilityRecord, Integer> CLASS_ID = createField("class_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>game.class_ability.ability_id</code>.
     */
    public final TableField<ClassAbilityRecord, Integer> ABILITY_ID = createField("ability_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * Create a <code>game.class_ability</code> table reference
     */
    public ClassAbility() {
        this("class_ability", null);
    }

    /**
     * Create an aliased <code>game.class_ability</code> table reference
     */
    public ClassAbility(String alias) {
        this(alias, CLASS_ABILITY);
    }

    private ClassAbility(String alias, Table<ClassAbilityRecord> aliased) {
        this(alias, aliased, null);
    }

    private ClassAbility(String alias, Table<ClassAbilityRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Game.GAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<ClassAbilityRecord> getPrimaryKey() {
        return Keys.CLASS_ABILITY_PKEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<ClassAbilityRecord>> getKeys() {
        return Arrays.<UniqueKey<ClassAbilityRecord>>asList(Keys.CLASS_ABILITY_PKEY, Keys.CLASS_ABILITY_CLASS_ID_ABILITY_ID_KEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<ClassAbilityRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<ClassAbilityRecord, ?>>asList(Keys.CLASS_ABILITY__FK_CLASS_ABILITY_CLASS_ID, Keys.CLASS_ABILITY__FK_CLASS_ABILITY_ABILITY_ID);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ClassAbility as(String alias) {
        return new ClassAbility(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public ClassAbility rename(String name) {
        return new ClassAbility(name, null);
    }
}
