/*
 * This file is generated by jOOQ.
*/
package com.sukitsuki.bot.jooq.game.tables;


import com.sukitsuki.bot.jooq.game.Game;
import com.sukitsuki.bot.jooq.game.Keys;
import com.sukitsuki.bot.jooq.game.tables.records.EntityStatusEffectRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EntityStatusEffect extends TableImpl<EntityStatusEffectRecord> {

    private static final long serialVersionUID = 1831659419;

    /**
     * The reference instance of <code>game.entity_status_effect</code>
     */
    public static final EntityStatusEffect ENTITY_STATUS_EFFECT = new EntityStatusEffect();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<EntityStatusEffectRecord> getRecordType() {
        return EntityStatusEffectRecord.class;
    }

    /**
     * The column <code>game.entity_status_effect.entity_status_effect_id</code>.
     */
    public final TableField<EntityStatusEffectRecord, Integer> ENTITY_STATUS_EFFECT_ID = createField("entity_status_effect_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>game.entity_status_effect.entity_id</code>.
     */
    public final TableField<EntityStatusEffectRecord, Integer> ENTITY_ID = createField("entity_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>game.entity_status_effect.status_effect_id</code>.
     */
    public final TableField<EntityStatusEffectRecord, Integer> STATUS_EFFECT_ID = createField("status_effect_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>game.entity_status_effect.date</code>.
     */
    public final TableField<EntityStatusEffectRecord, Timestamp> DATE = createField("date", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(org.jooq.impl.DSL.field("now()", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "");

    /**
     * Create a <code>game.entity_status_effect</code> table reference
     */
    public EntityStatusEffect() {
        this("entity_status_effect", null);
    }

    /**
     * Create an aliased <code>game.entity_status_effect</code> table reference
     */
    public EntityStatusEffect(String alias) {
        this(alias, ENTITY_STATUS_EFFECT);
    }

    private EntityStatusEffect(String alias, Table<EntityStatusEffectRecord> aliased) {
        this(alias, aliased, null);
    }

    private EntityStatusEffect(String alias, Table<EntityStatusEffectRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Game.GAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<EntityStatusEffectRecord> getPrimaryKey() {
        return Keys.ENTITY_STATUS_EFFECT_PKEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<EntityStatusEffectRecord>> getKeys() {
        return Arrays.<UniqueKey<EntityStatusEffectRecord>>asList(Keys.ENTITY_STATUS_EFFECT_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<EntityStatusEffectRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<EntityStatusEffectRecord, ?>>asList(Keys.ENTITY_STATUS_EFFECT__FK_ENTITY_STATUS_EFFECT_ENTITY_ID, Keys.ENTITY_STATUS_EFFECT__FK_ENTITY_STATUS_EFFECT_STATUS_EFFECT_ID);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EntityStatusEffect as(String alias) {
        return new EntityStatusEffect(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public EntityStatusEffect rename(String name) {
        return new EntityStatusEffect(name, null);
    }
}
