/*
 * This file is generated by jOOQ.
*/
package com.sukitsuki.bot.jooq.game.tables;


import com.sukitsuki.bot.jooq.game.Game;
import com.sukitsuki.bot.jooq.game.Keys;
import com.sukitsuki.bot.jooq.game.tables.records.EntityRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Entity extends TableImpl<EntityRecord> {

    private static final long serialVersionUID = -51566536;

    /**
     * The reference instance of <code>game.entity</code>
     */
    public static final Entity ENTITY = new Entity();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<EntityRecord> getRecordType() {
        return EntityRecord.class;
    }

    /**
     * The column <code>game.entity.entity_id</code>.
     */
    public final TableField<EntityRecord, Integer> ENTITY_ID = createField("entity_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>game.entity.entity_type_id</code>.
     */
    public final TableField<EntityRecord, Integer> ENTITY_TYPE_ID = createField("entity_type_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>game.entity.name</code>.
     */
    public final TableField<EntityRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(510).nullable(false), this, "");

    /**
     * The column <code>game.entity.level</code>.
     */
    public final TableField<EntityRecord, Short> LEVEL = createField("level", org.jooq.impl.SQLDataType.SMALLINT, this, "");

    /**
     * Create a <code>game.entity</code> table reference
     */
    public Entity() {
        this("entity", null);
    }

    /**
     * Create an aliased <code>game.entity</code> table reference
     */
    public Entity(String alias) {
        this(alias, ENTITY);
    }

    private Entity(String alias, Table<EntityRecord> aliased) {
        this(alias, aliased, null);
    }

    private Entity(String alias, Table<EntityRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Game.GAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<EntityRecord> getPrimaryKey() {
        return Keys.ENTITY_PKEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<EntityRecord>> getKeys() {
        return Arrays.<UniqueKey<EntityRecord>>asList(Keys.ENTITY_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<EntityRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<EntityRecord, ?>>asList(Keys.ENTITY__FK_ENTITY_ENTITY_TYPE_ID);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Entity as(String alias) {
        return new Entity(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Entity rename(String name) {
        return new Entity(name, null);
    }
}
