/*
 * This file is generated by jOOQ.
*/
package com.sukitsuki.bot.jooq.game.tables;


import com.sukitsuki.bot.jooq.game.Game;
import com.sukitsuki.bot.jooq.game.Keys;
import com.sukitsuki.bot.jooq.game.tables.records.EntityLootRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EntityLoot extends TableImpl<EntityLootRecord> {

    private static final long serialVersionUID = -997628503;

    /**
     * The reference instance of <code>game.entity_loot</code>
     */
    public static final EntityLoot ENTITY_LOOT = new EntityLoot();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<EntityLootRecord> getRecordType() {
        return EntityLootRecord.class;
    }

    /**
     * The column <code>game.entity_loot.entity_loot_id</code>.
     */
    public final TableField<EntityLootRecord, Integer> ENTITY_LOOT_ID = createField("entity_loot_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>game.entity_loot.loot_id</code>.
     */
    public final TableField<EntityLootRecord, Integer> LOOT_ID = createField("loot_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>game.entity_loot.entity_id</code>.
     */
    public final TableField<EntityLootRecord, Integer> ENTITY_ID = createField("entity_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * Create a <code>game.entity_loot</code> table reference
     */
    public EntityLoot() {
        this("entity_loot", null);
    }

    /**
     * Create an aliased <code>game.entity_loot</code> table reference
     */
    public EntityLoot(String alias) {
        this(alias, ENTITY_LOOT);
    }

    private EntityLoot(String alias, Table<EntityLootRecord> aliased) {
        this(alias, aliased, null);
    }

    private EntityLoot(String alias, Table<EntityLootRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Game.GAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<EntityLootRecord> getPrimaryKey() {
        return Keys.ENTITY_LOOT_PKEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<EntityLootRecord>> getKeys() {
        return Arrays.<UniqueKey<EntityLootRecord>>asList(Keys.ENTITY_LOOT_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<EntityLootRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<EntityLootRecord, ?>>asList(Keys.ENTITY_LOOT__FK_ENTITY_LOOT_LOOT_ID, Keys.ENTITY_LOOT__FK_ENTITY_LOOT_ENTITY_ID);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EntityLoot as(String alias) {
        return new EntityLoot(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public EntityLoot rename(String name) {
        return new EntityLoot(name, null);
    }
}
