/*
 * This file is generated by jOOQ.
*/
package com.sukitsuki.bot.jooq.game.tables;


import com.sukitsuki.bot.jooq.game.Game;
import com.sukitsuki.bot.jooq.game.Keys;
import com.sukitsuki.bot.jooq.game.tables.records.GuildRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Guild extends TableImpl<GuildRecord> {

    private static final long serialVersionUID = 386649017;

    /**
     * The reference instance of <code>game.guild</code>
     */
    public static final Guild GUILD = new Guild();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<GuildRecord> getRecordType() {
        return GuildRecord.class;
    }

    /**
     * The column <code>game.guild.guild_id</code>.
     */
    public final TableField<GuildRecord, Integer> GUILD_ID = createField("guild_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>game.guild.name</code>.
     */
    public final TableField<GuildRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(510).nullable(false), this, "");

    /**
     * Create a <code>game.guild</code> table reference
     */
    public Guild() {
        this("guild", null);
    }

    /**
     * Create an aliased <code>game.guild</code> table reference
     */
    public Guild(String alias) {
        this(alias, GUILD);
    }

    private Guild(String alias, Table<GuildRecord> aliased) {
        this(alias, aliased, null);
    }

    private Guild(String alias, Table<GuildRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Game.GAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<GuildRecord> getPrimaryKey() {
        return Keys.GUILD_PKEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<GuildRecord>> getKeys() {
        return Arrays.<UniqueKey<GuildRecord>>asList(Keys.GUILD_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Guild as(String alias) {
        return new Guild(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Guild rename(String name) {
        return new Guild(name, null);
    }
}
