/*
 * This file is generated by jOOQ.
*/
package com.sukitsuki.bot.jooq.game.tables;


import com.sukitsuki.bot.jooq.game.Game;
import com.sukitsuki.bot.jooq.game.Keys;
import com.sukitsuki.bot.jooq.game.tables.records.ItemTypeRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ItemType extends TableImpl<ItemTypeRecord> {

    private static final long serialVersionUID = 1905674309;

    /**
     * The reference instance of <code>game.item_type</code>
     */
    public static final ItemType ITEM_TYPE = new ItemType();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ItemTypeRecord> getRecordType() {
        return ItemTypeRecord.class;
    }

    /**
     * The column <code>game.item_type.item_type_id</code>.
     */
    public final TableField<ItemTypeRecord, Integer> ITEM_TYPE_ID = createField("item_type_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>game.item_type.name</code>.
     */
    public final TableField<ItemTypeRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(510).nullable(false), this, "");

    /**
     * The column <code>game.item_type.desc</code>.
     */
    public final TableField<ItemTypeRecord, String> DESC = createField("desc", org.jooq.impl.SQLDataType.VARCHAR.length(510).defaultValue(org.jooq.impl.DSL.field("NULL::character varying", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * Create a <code>game.item_type</code> table reference
     */
    public ItemType() {
        this("item_type", null);
    }

    /**
     * Create an aliased <code>game.item_type</code> table reference
     */
    public ItemType(String alias) {
        this(alias, ITEM_TYPE);
    }

    private ItemType(String alias, Table<ItemTypeRecord> aliased) {
        this(alias, aliased, null);
    }

    private ItemType(String alias, Table<ItemTypeRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Game.GAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<ItemTypeRecord> getPrimaryKey() {
        return Keys.ITEM_TYPE_PKEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<ItemTypeRecord>> getKeys() {
        return Arrays.<UniqueKey<ItemTypeRecord>>asList(Keys.ITEM_TYPE_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ItemType as(String alias) {
        return new ItemType(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public ItemType rename(String name) {
        return new ItemType(name, null);
    }
}
