/*
 * This file is generated by jOOQ.
*/
package com.sukitsuki.bot.jooq.game.tables;


import com.sukitsuki.bot.jooq.game.Game;
import com.sukitsuki.bot.jooq.game.Keys;
import com.sukitsuki.bot.jooq.game.tables.records.ItemLootRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ItemLoot extends TableImpl<ItemLootRecord> {

    private static final long serialVersionUID = 555204920;

    /**
     * The reference instance of <code>game.item_loot</code>
     */
    public static final ItemLoot ITEM_LOOT = new ItemLoot();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ItemLootRecord> getRecordType() {
        return ItemLootRecord.class;
    }

    /**
     * The column <code>game.item_loot.item_loot_id</code>.
     */
    public final TableField<ItemLootRecord, Integer> ITEM_LOOT_ID = createField("item_loot_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>game.item_loot.loot_id</code>.
     */
    public final TableField<ItemLootRecord, Integer> LOOT_ID = createField("loot_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>game.item_loot.item_id</code>.
     */
    public final TableField<ItemLootRecord, Integer> ITEM_ID = createField("item_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>game.item_loot.drop_chance</code>.
     */
    public final TableField<ItemLootRecord, Float> DROP_CHANCE = createField("drop_chance", org.jooq.impl.SQLDataType.REAL, this, "");

    /**
     * Create a <code>game.item_loot</code> table reference
     */
    public ItemLoot() {
        this("item_loot", null);
    }

    /**
     * Create an aliased <code>game.item_loot</code> table reference
     */
    public ItemLoot(String alias) {
        this(alias, ITEM_LOOT);
    }

    private ItemLoot(String alias, Table<ItemLootRecord> aliased) {
        this(alias, aliased, null);
    }

    private ItemLoot(String alias, Table<ItemLootRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Game.GAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<ItemLootRecord> getPrimaryKey() {
        return Keys.ITEM_LOOT_PKEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<ItemLootRecord>> getKeys() {
        return Arrays.<UniqueKey<ItemLootRecord>>asList(Keys.ITEM_LOOT_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<ItemLootRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<ItemLootRecord, ?>>asList(Keys.ITEM_LOOT__FK_ITEM_LOOT_LOOT_ID, Keys.ITEM_LOOT__FK_ITEM_LOOT_ITEM_ID);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ItemLoot as(String alias) {
        return new ItemLoot(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public ItemLoot rename(String name) {
        return new ItemLoot(name, null);
    }
}
