/*
 * This file is generated by jOOQ.
*/
package com.sukitsuki.bot.jooq.game.tables;


import com.sukitsuki.bot.jooq.game.Game;
import com.sukitsuki.bot.jooq.game.Keys;
import com.sukitsuki.bot.jooq.game.tables.records.RankRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Rank extends TableImpl<RankRecord> {

    private static final long serialVersionUID = -1738985688;

    /**
     * The reference instance of <code>game.rank</code>
     */
    public static final Rank RANK = new Rank();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<RankRecord> getRecordType() {
        return RankRecord.class;
    }

    /**
     * The column <code>game.rank.rank_id</code>.
     */
    public final TableField<RankRecord, Integer> RANK_ID = createField("rank_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>game.rank.name</code>.
     */
    public final TableField<RankRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(510).nullable(false), this, "");

    /**
     * Create a <code>game.rank</code> table reference
     */
    public Rank() {
        this("rank", null);
    }

    /**
     * Create an aliased <code>game.rank</code> table reference
     */
    public Rank(String alias) {
        this(alias, RANK);
    }

    private Rank(String alias, Table<RankRecord> aliased) {
        this(alias, aliased, null);
    }

    private Rank(String alias, Table<RankRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Game.GAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<RankRecord> getPrimaryKey() {
        return Keys.RANK_PKEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<RankRecord>> getKeys() {
        return Arrays.<UniqueKey<RankRecord>>asList(Keys.RANK_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Rank as(String alias) {
        return new Rank(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Rank rename(String name) {
        return new Rank(name, null);
    }
}
