/*
 * This file is generated by jOOQ.
*/
package com.sukitsuki.bot.jooq.game.tables;


import com.sukitsuki.bot.jooq.game.Game;
import com.sukitsuki.bot.jooq.game.Keys;
import com.sukitsuki.bot.jooq.game.tables.records.StatusEffectRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class StatusEffect extends TableImpl<StatusEffectRecord> {

    private static final long serialVersionUID = 130797099;

    /**
     * The reference instance of <code>game.status_effect</code>
     */
    public static final StatusEffect STATUS_EFFECT = new StatusEffect();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<StatusEffectRecord> getRecordType() {
        return StatusEffectRecord.class;
    }

    /**
     * The column <code>game.status_effect.status_effect_id</code>.
     */
    public final TableField<StatusEffectRecord, Integer> STATUS_EFFECT_ID = createField("status_effect_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>game.status_effect.name</code>.
     */
    public final TableField<StatusEffectRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(510).nullable(false), this, "");

    /**
     * The column <code>game.status_effect.effect_type_id</code>.
     */
    public final TableField<StatusEffectRecord, Integer> EFFECT_TYPE_ID = createField("effect_type_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>game.status_effect.duration</code>.
     */
    public final TableField<StatusEffectRecord, Long> DURATION = createField("duration", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>game.status_effect.desc</code>.
     */
    public final TableField<StatusEffectRecord, String> DESC = createField("desc", org.jooq.impl.SQLDataType.VARCHAR.length(510).defaultValue(org.jooq.impl.DSL.field("NULL::character varying", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * Create a <code>game.status_effect</code> table reference
     */
    public StatusEffect() {
        this("status_effect", null);
    }

    /**
     * Create an aliased <code>game.status_effect</code> table reference
     */
    public StatusEffect(String alias) {
        this(alias, STATUS_EFFECT);
    }

    private StatusEffect(String alias, Table<StatusEffectRecord> aliased) {
        this(alias, aliased, null);
    }

    private StatusEffect(String alias, Table<StatusEffectRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Game.GAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<StatusEffectRecord> getPrimaryKey() {
        return Keys.STATUS_EFFECT_PKEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<StatusEffectRecord>> getKeys() {
        return Arrays.<UniqueKey<StatusEffectRecord>>asList(Keys.STATUS_EFFECT_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<StatusEffectRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<StatusEffectRecord, ?>>asList(Keys.STATUS_EFFECT__FK_STATUS_EFFECT_EFFECT_TYPE_ID);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StatusEffect as(String alias) {
        return new StatusEffect(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public StatusEffect rename(String name) {
        return new StatusEffect(name, null);
    }
}
