/*
 * This file is generated by jOOQ.
*/
package com.sukitsuki.bot.jooq.game.tables;


import com.sukitsuki.bot.jooq.game.Game;
import com.sukitsuki.bot.jooq.game.Keys;
import com.sukitsuki.bot.jooq.game.tables.records.TitleRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Title extends TableImpl<TitleRecord> {

    private static final long serialVersionUID = 1048728058;

    /**
     * The reference instance of <code>game.title</code>
     */
    public static final Title TITLE = new Title();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TitleRecord> getRecordType() {
        return TitleRecord.class;
    }

    /**
     * The column <code>game.title.title_id</code>.
     */
    public final TableField<TitleRecord, Integer> TITLE_ID = createField("title_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>game.title.name</code>.
     */
    public final TableField<TitleRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(510).nullable(false), this, "");

    /**
     * Create a <code>game.title</code> table reference
     */
    public Title() {
        this("title", null);
    }

    /**
     * Create an aliased <code>game.title</code> table reference
     */
    public Title(String alias) {
        this(alias, TITLE);
    }

    private Title(String alias, Table<TitleRecord> aliased) {
        this(alias, aliased, null);
    }

    private Title(String alias, Table<TitleRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Game.GAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<TitleRecord> getPrimaryKey() {
        return Keys.TITLE_PKEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<TitleRecord>> getKeys() {
        return Arrays.<UniqueKey<TitleRecord>>asList(Keys.TITLE_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Title as(String alias) {
        return new Title(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Title rename(String name) {
        return new Title(name, null);
    }
}
