/*
 * This file is generated by jOOQ.
*/
package com.sukitsuki.bot.jooq.game.tables;


import com.sukitsuki.bot.jooq.game.Game;
import com.sukitsuki.bot.jooq.game.Keys;
import com.sukitsuki.bot.jooq.game.tables.records.UserTypeRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserType extends TableImpl<UserTypeRecord> {

    private static final long serialVersionUID = -230910570;

    /**
     * The reference instance of <code>game.user_type</code>
     */
    public static final UserType USER_TYPE = new UserType();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<UserTypeRecord> getRecordType() {
        return UserTypeRecord.class;
    }

    /**
     * The column <code>game.user_type.user_type_id</code>.
     */
    public final TableField<UserTypeRecord, Integer> USER_TYPE_ID = createField("user_type_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>game.user_type.name</code>.
     */
    public final TableField<UserTypeRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(510).nullable(false), this, "");

    /**
     * Create a <code>game.user_type</code> table reference
     */
    public UserType() {
        this("user_type", null);
    }

    /**
     * Create an aliased <code>game.user_type</code> table reference
     */
    public UserType(String alias) {
        this(alias, USER_TYPE);
    }

    private UserType(String alias, Table<UserTypeRecord> aliased) {
        this(alias, aliased, null);
    }

    private UserType(String alias, Table<UserTypeRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Game.GAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<UserTypeRecord> getPrimaryKey() {
        return Keys.USER_TYPE_PKEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<UserTypeRecord>> getKeys() {
        return Arrays.<UniqueKey<UserTypeRecord>>asList(Keys.USER_TYPE_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserType as(String alias) {
        return new UserType(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public UserType rename(String name) {
        return new UserType(name, null);
    }
}
