/*
 * This file is generated by jOOQ.
*/
package com.sukitsuki.bot.jooq.game.tables;


import com.sukitsuki.bot.jooq.game.Game;
import com.sukitsuki.bot.jooq.game.Keys;
import com.sukitsuki.bot.jooq.game.tables.records.UserCharacterRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserCharacter extends TableImpl<UserCharacterRecord> {

    private static final long serialVersionUID = -762431111;

    /**
     * The reference instance of <code>game.user_character</code>
     */
    public static final UserCharacter USER_CHARACTER = new UserCharacter();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<UserCharacterRecord> getRecordType() {
        return UserCharacterRecord.class;
    }

    /**
     * The column <code>game.user_character.user_character_id</code>.
     */
    public final TableField<UserCharacterRecord, Integer> USER_CHARACTER_ID = createField("user_character_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>game.user_character.user_id</code>.
     */
    public final TableField<UserCharacterRecord, Integer> USER_ID = createField("user_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>game.user_character.character_id</code>.
     */
    public final TableField<UserCharacterRecord, Integer> CHARACTER_ID = createField("character_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * Create a <code>game.user_character</code> table reference
     */
    public UserCharacter() {
        this("user_character", null);
    }

    /**
     * Create an aliased <code>game.user_character</code> table reference
     */
    public UserCharacter(String alias) {
        this(alias, USER_CHARACTER);
    }

    private UserCharacter(String alias, Table<UserCharacterRecord> aliased) {
        this(alias, aliased, null);
    }

    private UserCharacter(String alias, Table<UserCharacterRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Game.GAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<UserCharacterRecord> getPrimaryKey() {
        return Keys.USER_CHARACTER_PKEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<UserCharacterRecord>> getKeys() {
        return Arrays.<UniqueKey<UserCharacterRecord>>asList(Keys.USER_CHARACTER_PKEY, Keys.USER_CHARACTER_USER_ID_CHARACTER_ID_KEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<UserCharacterRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<UserCharacterRecord, ?>>asList(Keys.USER_CHARACTER__FK_USER_CHARACTER_USER_ID, Keys.USER_CHARACTER__FK_USER_CHARACTER_CHARACTER_ID);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserCharacter as(String alias) {
        return new UserCharacter(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public UserCharacter rename(String name) {
        return new UserCharacter(name, null);
    }
}
